import * as Breeding from 'containers/pages/breeding';
import i18n from 'i18next';

export const BreedingRouteList = [
  {
    uri: '/breeding/standard/00',
    page: Breeding.Standard.Page00,
    type: 'breeding',
    cate: 'standard',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#00'),
    is_full: false
  },
  {
    uri: '/breeding/standard/01',
    page: Breeding.Standard.Page01,
    type: 'breeding',
    cate: 'standard',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#01'),
    is_full: false
  },
  {
    uri: '/breeding/standard/02',
    page: Breeding.Standard.Page02,
    type: 'breeding',
    cate: 'standard',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#02'),
    is_full: false
  },
  {
    uri: '/breeding/standard/03',
    page: Breeding.Standard.Page03,
    type: 'breeding',
    cate: 'standard',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#03'),
    is_full: false
  },
  {
    uri: '/breeding/standard/04',
    page: Breeding.Standard.Page04,
    type: 'breeding',
    cate: 'standard',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#04'),
    is_full: false
  },
  {
    uri: '/breeding/standard/05',
    page: Breeding.Standard.Page05,
    type: 'breeding',
    cate: 'standard',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#05'),
    is_full: false
  },
  {
    uri: '/breeding/standard/06',
    page: Breeding.Standard.Page06,
    type: 'breeding',
    cate: 'standard',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#06'),
    is_full: false
  },
  {
    uri: '/breeding/standard/07',
    page: Breeding.Standard.Page07,
    type: 'breeding',
    cate: 'standard',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#07'),
    is_full: false
  },
  {
    uri: '/breeding/standard/08',
    page: Breeding.Standard.Page08,
    type: 'breeding',
    cate: 'standard',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#08'),
    is_full: false
  },
  {
    uri: '/breeding/standard/09',
    page: Breeding.Standard.Page09,
    type: 'breeding',
    cate: 'standard',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#09'),
    is_full: false
  },
  {
    uri: '/breeding/standard/10',
    page: Breeding.Standard.Page10,
    type: 'breeding',
    cate: 'standard',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#10'),
    is_full: false
  },
  {
    uri: '/breeding/standard/11',
    page: Breeding.Standard.Page11,
    type: 'breeding',
    cate: 'standard',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#11'),
    is_full: false
  },
  {
    uri: '/breeding/standard/12',
    page: Breeding.Standard.Page12,
    type: 'breeding',
    cate: 'standard',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#12'),
    is_full: false
  },
  {
    uri: '/breeding/standard/13',
    page: Breeding.Standard.Page13,
    type: 'breeding',
    cate: 'standard',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#13'),
    is_full: false
  },
  {
    uri: '/breeding/standard/14',
    page: Breeding.Standard.Page14,
    type: 'breeding',
    cate: 'standard',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#14'),
    is_full: false
  },
  {
    uri: '/breeding/standard/15',
    page: Breeding.Standard.Page15,
    type: 'breeding',
    cate: 'standard',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#15'),
    is_full: false
  },
  {
    uri: '/breeding/standard/16',
    page: Breeding.Standard.Page16,
    type: 'breeding',
    cate: 'standard',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#16'),
    is_full: false
  },
  {
    uri: '/breeding/standard/17',
    page: Breeding.Standard.Page17,
    type: 'breeding',
    cate: 'standard',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#17'),
    is_full: false
  },
  {
    uri: '/breeding/standard/18',
    page: Breeding.Standard.Page18,
    type: 'breeding',
    cate: 'standard',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#18'),
    is_full: false
  },
  {
    uri: '/breeding/standard/19',
    page: Breeding.Standard.Page19,
    type: 'breeding',
    cate: 'standard',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#19'),
    is_full: false
  },
  {
    uri: '/breeding/standard/20',
    page: Breeding.Standard.Page20,
    type: 'breeding',
    cate: 'standard',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#20'),
    is_full: false
  },
  {
    uri: '/breeding/standard/21',
    page: Breeding.Standard.Page21,
    type: 'breeding',
    cate: 'standard',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#21'),
    is_full: false
  },
  {
    uri: '/breeding/standard/22',
    page: Breeding.Standard.Page22,
    type: 'breeding',
    cate: 'standard',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#22'),
    is_full: false
  },
  {
    uri: '/breeding/standard/23',
    page: Breeding.Standard.Page23,
    type: 'breeding',
    cate: 'standard',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#23'),
    is_full: false
  },
  {
    uri: '/breeding/standard/24',
    page: Breeding.Standard.Page24,
    type: 'breeding',
    cate: 'standard',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#24'),
    is_full: false
  },
  {
    uri: '/breeding/standard/25',
    page: Breeding.Standard.Page25,
    type: 'breeding',
    cate: 'standard',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#25'),
    is_full: false
  },
  {
    uri: '/breeding/standard/26',
    page: Breeding.Standard.Page26,
    type: 'breeding',
    cate: 'standard',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#26'),
    is_full: false
  },
  {
    uri: '/breeding/standard/27',
    page: Breeding.Standard.Page27,
    type: 'breeding',
    cate: 'standard',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#27'),
    is_full: false
  },
  {
    uri: '/breeding/standard/28',
    page: Breeding.Standard.Page28,
    type: 'breeding',
    cate: 'standard',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#28'),
    is_full: false
  },
  {
    uri: '/breeding/standard/29',
    page: Breeding.Standard.Page29,
    type: 'breeding',
    cate: 'standard',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#29'),
    is_full: false
  },
  {
    uri: '/breeding/standard/30',
    page: Breeding.Standard.Page30,
    type: 'breeding',
    cate: 'standard',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('표준성적'),
    cate_desc: i18n.t('표준성적을 등록 수정 합니다'),
    page_nm: i18n.t('표준성적관리#30'),
    is_full: false
  },

  {
    uri: '/breeding/work/00',
    page: Breeding.Work.Page00,
    type: 'breeding',
    cate: 'work',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#00'),
    is_full: false
  },
  {
    uri: '/breeding/work/01',
    page: Breeding.Work.Page01,
    type: 'breeding',
    cate: 'work',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#01'),
    is_full: false
  },
  {
    uri: '/breeding/work/02',
    page: Breeding.Work.Page02,
    type: 'breeding',
    cate: 'work',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#02'),
    is_full: false
  },
  {
    uri: '/breeding/work/03',
    page: Breeding.Work.Page03,
    type: 'breeding',
    cate: 'work',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#03'),
    is_full: false
  },
  {
    uri: '/breeding/work/04',
    page: Breeding.Work.Page04,
    type: 'breeding',
    cate: 'work',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#04'),
    is_full: false
  },
  {
    uri: '/breeding/work/05',
    page: Breeding.Work.Page05,
    type: 'breeding',
    cate: 'work',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#05'),
    is_full: false
  },
  {
    uri: '/breeding/work/06',
    page: Breeding.Work.Page06,
    type: 'breeding',
    cate: 'work',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#06'),
    is_full: false
  },
  {
    uri: '/breeding/work/07',
    page: Breeding.Work.Page07,
    type: 'breeding',
    cate: 'work',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#07'),
    is_full: false
  },
  {
    uri: '/breeding/work/08',
    page: Breeding.Work.Page08,
    type: 'breeding',
    cate: 'work',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#08'),
    is_full: false
  },
  {
    uri: '/breeding/work/09',
    page: Breeding.Work.Page09,
    type: 'breeding',
    cate: 'work',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#09'),
    is_full: false
  },
  {
    uri: '/breeding/work/10',
    page: Breeding.Work.Page10,
    type: 'breeding',
    cate: 'work',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#10'),
    is_full: false
  },
  {
    uri: '/breeding/work/11',
    page: Breeding.Work.Page11,
    type: 'breeding',
    cate: 'work',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#11'),
    is_full: false
  },
  {
    uri: '/breeding/work/12',
    page: Breeding.Work.Page12,
    type: 'breeding',
    cate: 'work',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#12'),
    is_full: false
  },
  {
    uri: '/breeding/work/13',
    page: Breeding.Work.Page13,
    type: 'breeding',
    cate: 'work',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#13'),
    is_full: false
  },
  {
    uri: '/breeding/work/14',
    page: Breeding.Work.Page14,
    type: 'breeding',
    cate: 'work',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#14'),
    is_full: false
  },
  {
    uri: '/breeding/work/15',
    page: Breeding.Work.Page15,
    type: 'breeding',
    cate: 'work',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#15'),
    is_full: false
  },
  {
    uri: '/breeding/work/16',
    page: Breeding.Work.Page16,
    type: 'breeding',
    cate: 'work',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#16'),
    is_full: false
  },
  {
    uri: '/breeding/work/17',
    page: Breeding.Work.Page17,
    type: 'breeding',
    cate: 'work',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#17'),
    is_full: false
  },
  {
    uri: '/breeding/work/18',
    page: Breeding.Work.Page18,
    type: 'breeding',
    cate: 'work',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#18'),
    is_full: false
  },
  {
    uri: '/breeding/work/19',
    page: Breeding.Work.Page19,
    type: 'breeding',
    cate: 'work',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#19'),
    is_full: false
  },
  {
    uri: '/breeding/work/20',
    page: Breeding.Work.Page20,
    type: 'breeding',
    cate: 'work',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#20'),
    is_full: false
  },
  {
    uri: '/breeding/work/21',
    page: Breeding.Work.Page21,
    type: 'breeding',
    cate: 'work',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#21'),
    is_full: false
  },
  {
    uri: '/breeding/work/22',
    page: Breeding.Work.Page22,
    type: 'breeding',
    cate: 'work',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#22'),
    is_full: false
  },
  {
    uri: '/breeding/work/23',
    page: Breeding.Work.Page23,
    type: 'breeding',
    cate: 'work',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#23'),
    is_full: false
  },
  {
    uri: '/breeding/work/24',
    page: Breeding.Work.Page24,
    type: 'breeding',
    cate: 'work',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#24'),
    is_full: false
  },
  {
    uri: '/breeding/work/25',
    page: Breeding.Work.Page25,
    type: 'breeding',
    cate: 'work',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#25'),
    is_full: false
  },
  {
    uri: '/breeding/work/26',
    page: Breeding.Work.Page26,
    type: 'breeding',
    cate: 'work',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#26'),
    is_full: false
  },
  {
    uri: '/breeding/work/27',
    page: Breeding.Work.Page27,
    type: 'breeding',
    cate: 'work',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#27'),
    is_full: false
  },
  {
    uri: '/breeding/work/28',
    page: Breeding.Work.Page28,
    type: 'breeding',
    cate: 'work',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#28'),
    is_full: false
  },
  {
    uri: '/breeding/work/29',
    page: Breeding.Work.Page29,
    type: 'breeding',
    cate: 'work',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#29'),
    is_full: false
  },
  {
    uri: '/breeding/work/30',
    page: Breeding.Work.Page30,
    type: 'breeding',
    cate: 'work',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('작업지시'),
    cate_desc: i18n.t('작업지시 내용을 등록 수정 합니다'),
    page_nm: i18n.t('작업지시관리#30'),
    is_full: false
  },

  {
    uri: '/breeding/matrials/00',
    page: Breeding.Matirials.Page00,
    type: 'breeding',
    cate: 'matrials',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#0'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/01',
    page: Breeding.Matirials.Page01,
    type: 'breeding',
    cate: 'matrials',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#01'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/02',
    page: Breeding.Matirials.Page02,
    type: 'breeding',
    cate: 'matrials',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#02'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/03',
    page: Breeding.Matirials.Page03,
    type: 'breeding',
    cate: 'matrials',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#03'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/04',
    page: Breeding.Matirials.Page04,
    type: 'breeding',
    cate: 'matrials',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#04'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/05',
    page: Breeding.Matirials.Page05,
    type: 'breeding',
    cate: 'matrials',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#05'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/06',
    page: Breeding.Matirials.Page06,
    type: 'breeding',
    cate: 'matrials',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#06'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/07',
    page: Breeding.Matirials.Page07,
    type: 'breeding',
    cate: 'matrials',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#07'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/08',
    page: Breeding.Matirials.Page08,
    type: 'breeding',
    cate: 'matrials',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#08'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/09',
    page: Breeding.Matirials.Page09,
    type: 'breeding',
    cate: 'matrials',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#09'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/10',
    page: Breeding.Matirials.Page10,
    type: 'breeding',
    cate: 'matrials',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#10'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/11',
    page: Breeding.Matirials.Page11,
    type: 'breeding',
    cate: 'matrials',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#11'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/12',
    page: Breeding.Matirials.Page12,
    type: 'breeding',
    cate: 'matrials',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#12'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/13',
    page: Breeding.Matirials.Page13,
    type: 'breeding',
    cate: 'matrials',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#13'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/14',
    page: Breeding.Matirials.Page14,
    type: 'breeding',
    cate: 'matrials',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#14'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/15',
    page: Breeding.Matirials.Page15,
    type: 'breeding',
    cate: 'matrials',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#15'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/16',
    page: Breeding.Matirials.Page16,
    type: 'breeding',
    cate: 'matrials',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#16'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/17',
    page: Breeding.Matirials.Page17,
    type: 'breeding',
    cate: 'matrials',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#17'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/18',
    page: Breeding.Matirials.Page18,
    type: 'breeding',
    cate: 'matrials',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#18'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/19',
    page: Breeding.Matirials.Page19,
    type: 'breeding',
    cate: 'matrials',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#19'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/20',
    page: Breeding.Matirials.Page20,
    type: 'breeding',
    cate: 'matrials',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#20'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/21',
    page: Breeding.Matirials.Page21,
    type: 'breeding',
    cate: 'matrials',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#21'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/22',
    page: Breeding.Matirials.Page22,
    type: 'breeding',
    cate: 'matrials',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#22'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/23',
    page: Breeding.Matirials.Page23,
    type: 'breeding',
    cate: 'matrials',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#23'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/24',
    page: Breeding.Matirials.Page24,
    type: 'breeding',
    cate: 'matrials',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#24'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/25',
    page: Breeding.Matirials.Page25,
    type: 'breeding',
    cate: 'matrials',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#25'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/26',
    page: Breeding.Matirials.Page26,
    type: 'breeding',
    cate: 'matrials',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#26'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/27',
    page: Breeding.Matirials.Page27,
    type: 'breeding',
    cate: 'matrials',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#27'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/28',
    page: Breeding.Matirials.Page28,
    type: 'breeding',
    cate: 'matrials',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#28'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/29',
    page: Breeding.Matirials.Page29,
    type: 'breeding',
    cate: 'matrials',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#29'),
    is_full: false
  },
  {
    uri: '/breeding/matrials/30',
    page: Breeding.Matirials.Page30,
    type: 'breeding',
    cate: 'matrials',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('자재입출내역'),
    cate_desc: i18n.t('자재 입출 내역을 등록하고 수정할 수 있습니다'),
    page_nm: i18n.t('자재입출내역#30'),
    is_full: false
  },

  {
    uri: '/breeding/receive/00',
    page: Breeding.Receive.Page00,
    type: 'breeding',
    cate: 'receive',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#00'),
    is_full: false
  },
  {
    uri: '/breeding/receive/01',
    page: Breeding.Receive.Page01,
    type: 'breeding',
    cate: 'receive',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#01'),
    is_full: false
  },
  {
    uri: '/breeding/receive/02',
    page: Breeding.Receive.Page02,
    type: 'breeding',
    cate: 'receive',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#02'),
    is_full: false
  },
  {
    uri: '/breeding/receive/03',
    page: Breeding.Receive.Page03,
    type: 'breeding',
    cate: 'receive',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#03'),
    is_full: false
  },
  {
    uri: '/breeding/receive/04',
    page: Breeding.Receive.Page04,
    type: 'breeding',
    cate: 'receive',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#04'),
    is_full: false
  },
  {
    uri: '/breeding/receive/05',
    page: Breeding.Receive.Page05,
    type: 'breeding',
    cate: 'receive',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#05'),
    is_full: false
  },
  {
    uri: '/breeding/receive/06',
    page: Breeding.Receive.Page06,
    type: 'breeding',
    cate: 'receive',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#06'),
    is_full: false
  },
  {
    uri: '/breeding/receive/07',
    page: Breeding.Receive.Page07,
    type: 'breeding',
    cate: 'receive',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#07'),
    is_full: false
  },
  {
    uri: '/breeding/receive/08',
    page: Breeding.Receive.Page08,
    type: 'breeding',
    cate: 'receive',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#08'),
    is_full: false
  },
  {
    uri: '/breeding/receive/09',
    page: Breeding.Receive.Page09,
    type: 'breeding',
    cate: 'receive',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#09'),
    is_full: false
  },
  {
    uri: '/breeding/receive/20',
    page: Breeding.Receive.Page20,
    type: 'breeding',
    cate: 'receive',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#20'),
    is_full: false
  },
  {
    uri: '/breeding/receive/21',
    page: Breeding.Receive.Page21,
    type: 'breeding',
    cate: 'receive',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#21'),
    is_full: false
  },
  {
    uri: '/breeding/receive/22',
    page: Breeding.Receive.Page22,
    type: 'breeding',
    cate: 'receive',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#22'),
    is_full: false
  },
  {
    uri: '/breeding/receive/23',
    page: Breeding.Receive.Page23,
    type: 'breeding',
    cate: 'receive',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#23'),
    is_full: false
  },
  {
    uri: '/breeding/receive/24',
    page: Breeding.Receive.Page24,
    type: 'breeding',
    cate: 'receive',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#24'),
    is_full: false
  },
  {
    uri: '/breeding/receive/25',
    page: Breeding.Receive.Page25,
    type: 'breeding',
    cate: 'receive',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#25'),
    is_full: false
  },
  {
    uri: '/breeding/receive/26',
    page: Breeding.Receive.Page26,
    type: 'breeding',
    cate: 'receive',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#26'),
    is_full: false
  },
  {
    uri: '/breeding/receive/27',
    page: Breeding.Receive.Page27,
    type: 'breeding',
    cate: 'receive',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#27'),
    is_full: false
  },
  {
    uri: '/breeding/receive/28',
    page: Breeding.Receive.Page28,
    type: 'breeding',
    cate: 'receive',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#28'),
    is_full: false
  },
  {
    uri: '/breeding/receive/29',
    page: Breeding.Receive.Page29,
    type: 'breeding',
    cate: 'receive',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#29'),
    is_full: false
  },
  {
    uri: '/breeding/receive/30',
    page: Breeding.Receive.Page30,
    type: 'breeding',
    cate: 'receive',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('입고'),
    cate_desc: i18n.t('입고를 등록하고 수정합니다'),
    page_nm: i18n.t('입고#30'),
    is_full: false
  },

  {
    uri: '/breeding/growing/00',
    page: Breeding.Growing.Page00,
    type: 'breeding',
    cate: 'growing',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#00'),
    is_full: false
  },
  {
    uri: '/breeding/growing/01',
    page: Breeding.Growing.Page01,
    type: 'breeding',
    cate: 'growing',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#01'),
    is_full: false
  },
  {
    uri: '/breeding/growing/02',
    page: Breeding.Growing.Page02,
    type: 'breeding',
    cate: 'growing',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#02'),
    is_full: false
  },
  {
    uri: '/breeding/growing/03',
    page: Breeding.Growing.Page03,
    type: 'breeding',
    cate: 'growing',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#03'),
    is_full: false
  },
  {
    uri: '/breeding/growing/04',
    page: Breeding.Growing.Page04,
    type: 'breeding',
    cate: 'growing',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#04'),
    is_full: false
  },
  {
    uri: '/breeding/growing/05',
    page: Breeding.Growing.Page05,
    type: 'breeding',
    cate: 'growing',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#05'),
    is_full: false
  },
  {
    uri: '/breeding/growing/06',
    page: Breeding.Growing.Page06,
    type: 'breeding',
    cate: 'growing',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#06'),
    is_full: false
  },
  {
    uri: '/breeding/growing/07',
    page: Breeding.Growing.Page07,
    type: 'breeding',
    cate: 'growing',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#07'),
    is_full: false
  },
  {
    uri: '/breeding/growing/08',
    page: Breeding.Growing.Page08,
    type: 'breeding',
    cate: 'growing',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#08'),
    is_full: false
  },
  {
    uri: '/breeding/growing/09',
    page: Breeding.Growing.Page09,
    type: 'breeding',
    cate: 'growing',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#09'),
    is_full: false
  },
  {
    uri: '/breeding/growing/10',
    page: Breeding.Growing.Page10,
    type: 'breeding',
    cate: 'growing',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#10'),
    is_full: false
  },
  {
    uri: '/breeding/growing/11',
    page: Breeding.Growing.Page11,
    type: 'breeding',
    cate: 'growing',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#11'),
    is_full: false
  },
  {
    uri: '/breeding/growing/12',
    page: Breeding.Growing.Page12,
    type: 'breeding',
    cate: 'growing',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#12'),
    is_full: false
  },
  {
    uri: '/breeding/growing/13',
    page: Breeding.Growing.Page13,
    type: 'breeding',
    cate: 'growing',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#13'),
    is_full: false
  },
  {
    uri: '/breeding/growing/14',
    page: Breeding.Growing.Page14,
    type: 'breeding',
    cate: 'growing',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#14'),
    is_full: false
  },
  {
    uri: '/breeding/growing/15',
    page: Breeding.Growing.Page15,
    type: 'breeding',
    cate: 'growing',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#15'),
    is_full: false
  },
  {
    uri: '/breeding/growing/16',
    page: Breeding.Growing.Page16,
    type: 'breeding',
    cate: 'growing',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#16'),
    is_full: false
  },
  {
    uri: '/breeding/growing/17',
    page: Breeding.Growing.Page17,
    type: 'breeding',
    cate: 'growing',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#17'),
    is_full: false
  },
  {
    uri: '/breeding/growing/18',
    page: Breeding.Growing.Page18,
    type: 'breeding',
    cate: 'growing',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#18'),
    is_full: false
  },
  {
    uri: '/breeding/growing/19',
    page: Breeding.Growing.Page19,
    type: 'breeding',
    cate: 'growing',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#19'),
    is_full: false
  },
  {
    uri: '/breeding/growing/20',
    page: Breeding.Growing.Page20,
    type: 'breeding',
    cate: 'growing',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#20'),
    is_full: false
  },
  {
    uri: '/breeding/growing/21',
    page: Breeding.Growing.Page21,
    type: 'breeding',
    cate: 'growing',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#21'),
    is_full: false
  },
  {
    uri: '/breeding/growing/22',
    page: Breeding.Growing.Page22,
    type: 'breeding',
    cate: 'growing',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#22'),
    is_full: false
  },
  {
    uri: '/breeding/growing/23',
    page: Breeding.Growing.Page23,
    type: 'breeding',
    cate: 'growing',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#23'),
    is_full: false
  },
  {
    uri: '/breeding/growing/24',
    page: Breeding.Growing.Page24,
    type: 'breeding',
    cate: 'growing',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#24'),
    is_full: false
  },
  {
    uri: '/breeding/growing/25',
    page: Breeding.Growing.Page25,
    type: 'breeding',
    cate: 'growing',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#25'),
    is_full: false
  },
  {
    uri: '/breeding/growing/26',
    page: Breeding.Growing.Page26,
    type: 'breeding',
    cate: 'growing',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#26'),
    is_full: false
  },
  {
    uri: '/breeding/growing/27',
    page: Breeding.Growing.Page27,
    type: 'breeding',
    cate: 'growing',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#27'),
    is_full: false
  },
  {
    uri: '/breeding/growing/28',
    page: Breeding.Growing.Page28,
    type: 'breeding',
    cate: 'growing',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#28'),
    is_full: false
  },
  {
    uri: '/breeding/growing/29',
    page: Breeding.Growing.Page29,
    type: 'breeding',
    cate: 'growing',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#29'),
    is_full: false
  },
  {
    uri: '/breeding/growing/30',
    page: Breeding.Growing.Page30,
    type: 'breeding',
    cate: 'growing',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('성장관리'),
    cate_desc: i18n.t('사료,백신,성장정도를 일자별로 등록하고 수정 합니다'),
    page_nm: i18n.t('성장관리#30'),
    is_full: false
  },

  {
    uri: '/breeding/egg/00',
    page: Breeding.Egg.Page00,
    type: 'breeding',
    cate: 'egg',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#00'),
    is_full: false
  },
  {
    uri: '/breeding/egg/01',
    page: Breeding.Egg.Page01,
    type: 'breeding',
    cate: 'egg',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#01'),
    is_full: false
  },
  {
    uri: '/breeding/egg/02',
    page: Breeding.Egg.Page02,
    type: 'breeding',
    cate: 'egg',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#02'),
    is_full: false
  },
  {
    uri: '/breeding/egg/03',
    page: Breeding.Egg.Page03,
    type: 'breeding',
    cate: 'egg',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#03'),
    is_full: false
  },
  {
    uri: '/breeding/egg/04',
    page: Breeding.Egg.Page04,
    type: 'breeding',
    cate: 'egg',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#04'),
    is_full: false
  },
  {
    uri: '/breeding/egg/05',
    page: Breeding.Egg.Page05,
    type: 'breeding',
    cate: 'egg',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#05'),
    is_full: false
  },
  {
    uri: '/breeding/egg/06',
    page: Breeding.Egg.Page06,
    type: 'breeding',
    cate: 'egg',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#06'),
    is_full: false
  },
  {
    uri: '/breeding/egg/07',
    page: Breeding.Egg.Page07,
    type: 'breeding',
    cate: 'egg',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#07'),
    is_full: false
  },
  {
    uri: '/breeding/egg/08',
    page: Breeding.Egg.Page08,
    type: 'breeding',
    cate: 'egg',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#08'),
    is_full: false
  },
  {
    uri: '/breeding/egg/09',
    page: Breeding.Egg.Page09,
    type: 'breeding',
    cate: 'egg',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#09'),
    is_full: false
  },
  {
    uri: '/breeding/egg/10',
    page: Breeding.Egg.Page10,
    type: 'breeding',
    cate: 'egg',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#10'),
    is_full: false
  },
  {
    uri: '/breeding/egg/11',
    page: Breeding.Egg.Page11,
    type: 'breeding',
    cate: 'egg',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#11'),
    is_full: false
  },
  {
    uri: '/breeding/egg/12',
    page: Breeding.Egg.Page12,
    type: 'breeding',
    cate: 'egg',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#12'),
    is_full: false
  },
  {
    uri: '/breeding/egg/13',
    page: Breeding.Egg.Page13,
    type: 'breeding',
    cate: 'egg',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#13'),
    is_full: false
  },
  {
    uri: '/breeding/egg/14',
    page: Breeding.Egg.Page14,
    type: 'breeding',
    cate: 'egg',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#14'),
    is_full: false
  },
  {
    uri: '/breeding/egg/15',
    page: Breeding.Egg.Page15,
    type: 'breeding',
    cate: 'egg',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#15'),
    is_full: false
  },
  {
    uri: '/breeding/egg/16',
    page: Breeding.Egg.Page16,
    type: 'breeding',
    cate: 'egg',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#16'),
    is_full: false
  },
  {
    uri: '/breeding/egg/17',
    page: Breeding.Egg.Page17,
    type: 'breeding',
    cate: 'egg',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#17'),
    is_full: false
  },
  {
    uri: '/breeding/egg/18',
    page: Breeding.Egg.Page18,
    type: 'breeding',
    cate: 'egg',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#18'),
    is_full: false
  },
  {
    uri: '/breeding/egg/19',
    page: Breeding.Egg.Page19,
    type: 'breeding',
    cate: 'egg',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#19'),
    is_full: false
  },
  {
    uri: '/breeding/egg/20',
    page: Breeding.Egg.Page20,
    type: 'breeding',
    cate: 'egg',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#20'),
    is_full: false
  },
  {
    uri: '/breeding/egg/21',
    page: Breeding.Egg.Page21,
    type: 'breeding',
    cate: 'egg',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#21'),
    is_full: false
  },
  {
    uri: '/breeding/egg/22',
    page: Breeding.Egg.Page22,
    type: 'breeding',
    cate: 'egg',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#22'),
    is_full: false
  },
  {
    uri: '/breeding/egg/23',
    page: Breeding.Egg.Page23,
    type: 'breeding',
    cate: 'egg',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#23'),
    is_full: false
  },
  {
    uri: '/breeding/egg/24',
    page: Breeding.Egg.Page24,
    type: 'breeding',
    cate: 'egg',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#24'),
    is_full: false
  },
  {
    uri: '/breeding/egg/25',
    page: Breeding.Egg.Page25,
    type: 'breeding',
    cate: 'egg',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#25'),
    is_full: false
  },
  {
    uri: '/breeding/egg/26',
    page: Breeding.Egg.Page26,
    type: 'breeding',
    cate: 'egg',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#26'),
    is_full: false
  },
  {
    uri: '/breeding/egg/27',
    page: Breeding.Egg.Page27,
    type: 'breeding',
    cate: 'egg',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#27'),
    is_full: false
  },
  {
    uri: '/breeding/egg/28',
    page: Breeding.Egg.Page28,
    type: 'breeding',
    cate: 'egg',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#28'),
    is_full: false
  },
  {
    uri: '/breeding/egg/29',
    page: Breeding.Egg.Page29,
    type: 'breeding',
    cate: 'egg',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#29'),
    is_full: false
  },
  {
    uri: '/breeding/egg/30',
    page: Breeding.Egg.Page30,
    type: 'breeding',
    cate: 'egg',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('계사관리'),
    cate_desc: i18n.t(
      '계사별,일자별 생산된 계란의 수량과 상태 등록 및 수정 합니다'
    ),
    page_nm: i18n.t('계란관리#30'),
    is_full: false
  },

  {
    uri: '/breeding/release/00',
    page: Breeding.Release.Page00,
    type: 'breeding',
    cate: 'release',
    id: '00',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#00'),
    is_full: false
  },
  {
    uri: '/breeding/release/01',
    page: Breeding.Release.Page01,
    type: 'breeding',
    cate: 'release',
    id: '01',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#01'),
    is_full: false
  },
  {
    uri: '/breeding/release/02',
    page: Breeding.Release.Page02,
    type: 'breeding',
    cate: 'release',
    id: '02',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#02'),
    is_full: false
  },
  {
    uri: '/breeding/release/03',
    page: Breeding.Release.Page03,
    type: 'breeding',
    cate: 'release',
    id: '03',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#03'),
    is_full: false
  },
  {
    uri: '/breeding/release/04',
    page: Breeding.Release.Page04,
    type: 'breeding',
    cate: 'release',
    id: '04',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#04'),
    is_full: false
  },
  {
    uri: '/breeding/release/05',
    page: Breeding.Release.Page05,
    type: 'breeding',
    cate: 'release',
    id: '05',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#05'),
    is_full: false
  },
  {
    uri: '/breeding/release/06',
    page: Breeding.Release.Page06,
    type: 'breeding',
    cate: 'release',
    id: '06',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#06'),
    is_full: false
  },
  {
    uri: '/breeding/release/07',
    page: Breeding.Release.Page07,
    type: 'breeding',
    cate: 'release',
    id: '07',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#07'),
    is_full: false
  },
  {
    uri: '/breeding/release/08',
    page: Breeding.Release.Page08,
    type: 'breeding',
    cate: 'release',
    id: '08',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#08'),
    is_full: false
  },
  {
    uri: '/breeding/release/09',
    page: Breeding.Release.Page09,
    type: 'breeding',
    cate: 'release',
    id: '09',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#09'),
    is_full: false
  },
  {
    uri: '/breeding/release/10',
    page: Breeding.Release.Page10,
    type: 'breeding',
    cate: 'release',
    id: '10',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#10'),
    is_full: false
  },
  {
    uri: '/breeding/release/11',
    page: Breeding.Release.Page11,
    type: 'breeding',
    cate: 'release',
    id: '11',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#11'),
    is_full: false
  },
  {
    uri: '/breeding/release/12',
    page: Breeding.Release.Page12,
    type: 'breeding',
    cate: 'release',
    id: '12',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#12'),
    is_full: false
  },
  {
    uri: '/breeding/release/13',
    page: Breeding.Release.Page13,
    type: 'breeding',
    cate: 'release',
    id: '13',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#13'),
    is_full: false
  },
  {
    uri: '/breeding/release/14',
    page: Breeding.Release.Page14,
    type: 'breeding',
    cate: 'release',
    id: '14',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#14'),
    is_full: false
  },
  {
    uri: '/breeding/release/15',
    page: Breeding.Release.Page15,
    type: 'breeding',
    cate: 'release',
    id: '15',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#15'),
    is_full: false
  },
  {
    uri: '/breeding/release/16',
    page: Breeding.Release.Page16,
    type: 'breeding',
    cate: 'release',
    id: '16',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#16'),
    is_full: false
  },
  {
    uri: '/breeding/release/17',
    page: Breeding.Release.Page17,
    type: 'breeding',
    cate: 'release',
    id: '17',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#17'),
    is_full: false
  },
  {
    uri: '/breeding/release/18',
    page: Breeding.Release.Page18,
    type: 'breeding',
    cate: 'release',
    id: '18',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#18'),
    is_full: false
  },
  {
    uri: '/breeding/release/19',
    page: Breeding.Release.Page19,
    type: 'breeding',
    cate: 'release',
    id: '19',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#19'),
    is_full: false
  },
  {
    uri: '/breeding/release/20',
    page: Breeding.Release.Page20,
    type: 'breeding',
    cate: 'release',
    id: '20',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#20'),
    is_full: false
  },
  {
    uri: '/breeding/release/21',
    page: Breeding.Release.Page21,
    type: 'breeding',
    cate: 'release',
    id: '21',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#21'),
    is_full: false
  },
  {
    uri: '/breeding/release/22',
    page: Breeding.Release.Page22,
    type: 'breeding',
    cate: 'release',
    id: '22',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#22'),
    is_full: false
  },
  {
    uri: '/breeding/release/23',
    page: Breeding.Release.Page23,
    type: 'breeding',
    cate: 'release',
    id: '23',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#23'),
    is_full: false
  },
  {
    uri: '/breeding/release/24',
    page: Breeding.Release.Page24,
    type: 'breeding',
    cate: 'release',
    id: '24',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#24'),
    is_full: false
  },
  {
    uri: '/breeding/release/25',
    page: Breeding.Release.Page25,
    type: 'breeding',
    cate: 'release',
    id: '25',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#25'),
    is_full: false
  },
  {
    uri: '/breeding/release/26',
    page: Breeding.Release.Page26,
    type: 'breeding',
    cate: 'release',
    id: '26',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#26'),
    is_full: false
  },
  {
    uri: '/breeding/release/27',
    page: Breeding.Release.Page27,
    type: 'breeding',
    cate: 'release',
    id: '27',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#27'),
    is_full: false
  },
  {
    uri: '/breeding/release/28',
    page: Breeding.Release.Page28,
    type: 'breeding',
    cate: 'release',
    id: '28',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#28'),
    is_full: false
  },
  {
    uri: '/breeding/release/29',
    page: Breeding.Release.Page29,
    type: 'breeding',
    cate: 'release',
    id: '29',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#29'),
    is_full: false
  },
  {
    uri: '/breeding/release/30',
    page: Breeding.Release.Page30,
    type: 'breeding',
    cate: 'release',
    id: '30',
    type_nm: i18n.t('종계'),
    cate_nm: i18n.t('출고관리'),
    cate_desc: i18n.t('생산된 계란을 부화장으로 또는 판매, 폐기, 기부 합니다'),
    page_nm: i18n.t('출고#30'),
    is_full: false
  }
];
