import * as Broiler from 'containers/pages/broiler';
import i18n from 'i18next';

const BroilerRouteList = [
  {
    uri: '/broiler/receive/00',
    page: Broiler.Receive.Page00,
    type: 'broiler',
    cate: 'receive',
    id: '00',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/broiler/receive/01',
    page: Broiler.Receive.Page01,
    type: 'broiler',
    cate: 'receive',
    id: '01',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/broiler/receive/02',
    page: Broiler.Receive.Page02,
    type: 'broiler',
    cate: 'receive',
    id: '02',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/broiler/receive/03',
    page: Broiler.Receive.Page03,
    type: 'broiler',
    cate: 'receive',
    id: '03',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/broiler/receive/04',
    page: Broiler.Receive.Page04,
    type: 'broiler',
    cate: 'receive',
    id: '04',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/broiler/receive/05',
    page: Broiler.Receive.Page05,
    type: 'broiler',
    cate: 'receive',
    id: '05',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/broiler/receive/06',
    page: Broiler.Receive.Page06,
    type: 'broiler',
    cate: 'receive',
    id: '06',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/broiler/receive/07',
    page: Broiler.Receive.Page07,
    type: 'broiler',
    cate: 'receive',
    id: '07',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/broiler/receive/08',
    page: Broiler.Receive.Page08,
    type: 'broiler',
    cate: 'receive',
    id: '08',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/broiler/receive/09',
    page: Broiler.Receive.Page09,
    type: 'broiler',
    cate: 'receive',
    id: '09',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/broiler/receive/10',
    page: Broiler.Receive.Page10,
    type: 'broiler',
    cate: 'receive',
    id: '10',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/broiler/receive/11',
    page: Broiler.Receive.Page11,
    type: 'broiler',
    cate: 'receive',
    id: '11',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/broiler/receive/12',
    page: Broiler.Receive.Page12,
    type: 'broiler',
    cate: 'receive',
    id: '12',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/broiler/receive/13',
    page: Broiler.Receive.Page13,
    type: 'broiler',
    cate: 'receive',
    id: '13',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/broiler/receive/14',
    page: Broiler.Receive.Page14,
    type: 'broiler',
    cate: 'receive',
    id: '14',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/broiler/receive/15',
    page: Broiler.Receive.Page15,
    type: 'broiler',
    cate: 'receive',
    id: '15',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/broiler/receive/16',
    page: Broiler.Receive.Page16,
    type: 'broiler',
    cate: 'receive',
    id: '16',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/broiler/receive/17',
    page: Broiler.Receive.Page17,
    type: 'broiler',
    cate: 'receive',
    id: '17',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/broiler/receive/18',
    page: Broiler.Receive.Page18,
    type: 'broiler',
    cate: 'receive',
    id: '18',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/broiler/receive/19',
    page: Broiler.Receive.Page19,
    type: 'broiler',
    cate: 'receive',
    id: '19',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/broiler/receive/20',
    page: Broiler.Receive.Page20,
    type: 'broiler',
    cate: 'receive',
    id: '20',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/broiler/receive/21',
    page: Broiler.Receive.Page21,
    type: 'broiler',
    cate: 'receive',
    id: '21',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/broiler/receive/22',
    page: Broiler.Receive.Page22,
    type: 'broiler',
    cate: 'receive',
    id: '22',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/broiler/receive/23',
    page: Broiler.Receive.Page23,
    type: 'broiler',
    cate: 'receive',
    id: '23',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/broiler/receive/24',
    page: Broiler.Receive.Page24,
    type: 'broiler',
    cate: 'receive',
    id: '24',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/broiler/receive/25',
    page: Broiler.Receive.Page25,
    type: 'broiler',
    cate: 'receive',
    id: '25',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/broiler/receive/26',
    page: Broiler.Receive.Page26,
    type: 'broiler',
    cate: 'receive',
    id: '26',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/broiler/receive/27',
    page: Broiler.Receive.Page27,
    type: 'broiler',
    cate: 'receive',
    id: '27',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/broiler/receive/28',
    page: Broiler.Receive.Page28,
    type: 'broiler',
    cate: 'receive',
    id: '28',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/broiler/receive/29',
    page: Broiler.Receive.Page29,
    type: 'broiler',
    cate: 'receive',
    id: '29',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/broiler/receive/30',
    page: Broiler.Receive.Page30,
    type: 'broiler',
    cate: 'receive',
    id: '30',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('입고'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },
  {
    uri: '/broiler/growing/00',
    page: Broiler.Growing.Page00,
    type: 'broiler',
    cate: 'growing',
    id: '00',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/broiler/growing/01',
    page: Broiler.Growing.Page01,
    type: 'broiler',
    cate: 'growing',
    id: '01',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/broiler/growing/02',
    page: Broiler.Growing.Page02,
    type: 'broiler',
    cate: 'growing',
    id: '02',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/broiler/growing/03',
    page: Broiler.Growing.Page03,
    type: 'broiler',
    cate: 'growing',
    id: '03',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/broiler/growing/04',
    page: Broiler.Growing.Page04,
    type: 'broiler',
    cate: 'growing',
    id: '04',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/broiler/growing/05',
    page: Broiler.Growing.Page05,
    type: 'broiler',
    cate: 'growing',
    id: '05',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/broiler/growing/06',
    page: Broiler.Growing.Page06,
    type: 'broiler',
    cate: 'growing',
    id: '06',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/broiler/growing/07',
    page: Broiler.Growing.Page07,
    type: 'broiler',
    cate: 'growing',
    id: '07',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/broiler/growing/08',
    page: Broiler.Growing.Page08,
    type: 'broiler',
    cate: 'growing',
    id: '08',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/broiler/growing/09',
    page: Broiler.Growing.Page09,
    type: 'broiler',
    cate: 'growing',
    id: '09',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/broiler/growing/10',
    page: Broiler.Growing.Page10,
    type: 'broiler',
    cate: 'growing',
    id: '10',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/broiler/growing/11',
    page: Broiler.Growing.Page11,
    type: 'broiler',
    cate: 'growing',
    id: '11',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/broiler/growing/12',
    page: Broiler.Growing.Page12,
    type: 'broiler',
    cate: 'growing',
    id: '12',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/broiler/growing/13',
    page: Broiler.Growing.Page13,
    type: 'broiler',
    cate: 'growing',
    id: '13',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/broiler/growing/14',
    page: Broiler.Growing.Page14,
    type: 'broiler',
    cate: 'growing',
    id: '14',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/broiler/growing/15',
    page: Broiler.Growing.Page15,
    type: 'broiler',
    cate: 'growing',
    id: '15',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/broiler/growing/16',
    page: Broiler.Growing.Page16,
    type: 'broiler',
    cate: 'growing',
    id: '16',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/broiler/growing/17',
    page: Broiler.Growing.Page17,
    type: 'broiler',
    cate: 'growing',
    id: '17',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/broiler/growing/18',
    page: Broiler.Growing.Page18,
    type: 'broiler',
    cate: 'growing',
    id: '18',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/broiler/growing/19',
    page: Broiler.Growing.Page19,
    type: 'broiler',
    cate: 'growing',
    id: '19',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/broiler/growing/20',
    page: Broiler.Growing.Page20,
    type: 'broiler',
    cate: 'growing',
    id: '20',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/broiler/growing/21',
    page: Broiler.Growing.Page21,
    type: 'broiler',
    cate: 'growing',
    id: '21',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/broiler/growing/22',
    page: Broiler.Growing.Page22,
    type: 'broiler',
    cate: 'growing',
    id: '22',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/broiler/growing/23',
    page: Broiler.Growing.Page23,
    type: 'broiler',
    cate: 'growing',
    id: '23',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/broiler/growing/24',
    page: Broiler.Growing.Page24,
    type: 'broiler',
    cate: 'growing',
    id: '24',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/broiler/growing/25',
    page: Broiler.Growing.Page25,
    type: 'broiler',
    cate: 'growing',
    id: '25',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/broiler/growing/26',
    page: Broiler.Growing.Page26,
    type: 'broiler',
    cate: 'growing',
    id: '26',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/broiler/growing/27',
    page: Broiler.Growing.Page27,
    type: 'broiler',
    cate: 'growing',
    id: '27',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/broiler/growing/28',
    page: Broiler.Growing.Page28,
    type: 'broiler',
    cate: 'growing',
    id: '28',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/broiler/growing/29',
    page: Broiler.Growing.Page29,
    type: 'broiler',
    cate: 'growing',
    id: '29',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/broiler/growing/30',
    page: Broiler.Growing.Page30,
    type: 'broiler',
    cate: 'growing',
    id: '30',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('육성일지'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/00',
    page: Broiler.Transfer.Page00,
    type: 'broiler',
    cate: 'transfer',
    id: '00',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/01',
    page: Broiler.Transfer.Page01,
    type: 'broiler',
    cate: 'transfer',
    id: '01',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/02',
    page: Broiler.Transfer.Page02,
    type: 'broiler',
    cate: 'transfer',
    id: '02',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/03',
    page: Broiler.Transfer.Page03,
    type: 'broiler',
    cate: 'transfer',
    id: '03',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/04',
    page: Broiler.Transfer.Page04,
    type: 'broiler',
    cate: 'transfer',
    id: '04',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/05',
    page: Broiler.Transfer.Page05,
    type: 'broiler',
    cate: 'transfer',
    id: '05',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/06',
    page: Broiler.Transfer.Page06,
    type: 'broiler',
    cate: 'transfer',
    id: '06',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/07',
    page: Broiler.Transfer.Page07,
    type: 'broiler',
    cate: 'transfer',
    id: '07',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/08',
    page: Broiler.Transfer.Page08,
    type: 'broiler',
    cate: 'transfer',
    id: '08',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/09',
    page: Broiler.Transfer.Page09,
    type: 'broiler',
    cate: 'transfer',
    id: '09',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/10',
    page: Broiler.Transfer.Page10,
    type: 'broiler',
    cate: 'transfer',
    id: '10',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/11',
    page: Broiler.Transfer.Page11,
    type: 'broiler',
    cate: 'transfer',
    id: '11',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/12',
    page: Broiler.Transfer.Page12,
    type: 'broiler',
    cate: 'transfer',
    id: '12',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/13',
    page: Broiler.Transfer.Page13,
    type: 'broiler',
    cate: 'transfer',
    id: '13',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/14',
    page: Broiler.Transfer.Page14,
    type: 'broiler',
    cate: 'transfer',
    id: '14',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/15',
    page: Broiler.Transfer.Page15,
    type: 'broiler',
    cate: 'transfer',
    id: '15',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/16',
    page: Broiler.Transfer.Page16,
    type: 'broiler',
    cate: 'transfer',
    id: '16',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/17',
    page: Broiler.Transfer.Page17,
    type: 'broiler',
    cate: 'transfer',
    id: '17',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/18',
    page: Broiler.Transfer.Page18,
    type: 'broiler',
    cate: 'transfer',
    id: '18',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/19',
    page: Broiler.Transfer.Page19,
    type: 'broiler',
    cate: 'transfer',
    id: '19',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/20',
    page: Broiler.Transfer.Page20,
    type: 'broiler',
    cate: 'transfer',
    id: '20',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/21',
    page: Broiler.Transfer.Page21,
    type: 'broiler',
    cate: 'transfer',
    id: '21',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/22',
    page: Broiler.Transfer.Page22,
    type: 'broiler',
    cate: 'transfer',
    id: '22',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/23',
    page: Broiler.Transfer.Page23,
    type: 'broiler',
    cate: 'transfer',
    id: '23',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/24',
    page: Broiler.Transfer.Page24,
    type: 'broiler',
    cate: 'transfer',
    id: '24',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/25',
    page: Broiler.Transfer.Page25,
    type: 'broiler',
    cate: 'transfer',
    id: '25',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/26',
    page: Broiler.Transfer.Page26,
    type: 'broiler',
    cate: 'transfer',
    id: '26',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/27',
    page: Broiler.Transfer.Page27,
    type: 'broiler',
    cate: 'transfer',
    id: '27',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/28',
    page: Broiler.Transfer.Page28,
    type: 'broiler',
    cate: 'transfer',
    id: '28',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/29',
    page: Broiler.Transfer.Page29,
    type: 'broiler',
    cate: 'transfer',
    id: '29',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/broiler/transfer/30',
    page: Broiler.Transfer.Page30,
    type: 'broiler',
    cate: 'transfer',
    id: '30',
    type_nm: i18n.t('육계'),
    cate_nm: i18n.t('닭 출고'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  }
];
export default BroilerRouteList;
