import * as Common from 'containers/pages/common';
import i18n from 'i18next';

const CommonRouteList = [
  {
    uri: '/common/member/0',
    page: Common.Member.Page0,
    type: 'common',
    cate: 'member',
    id: '0',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#0'),
    is_full: false
  },
  {
    uri: '/common/member/1',
    page: Common.Member.Page1,
    type: 'common',
    cate: 'member',
    id: '1',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#1'),
    is_full: false
  },
  {
    uri: '/common/member/2',
    page: Common.Member.Page2,
    type: 'common',
    cate: 'member',
    id: '2',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#2'),
    is_full: false
  },
  {
    uri: '/common/member/3',
    page: Common.Member.Page3,
    type: 'common',
    cate: 'member',
    id: '3',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#3'),
    is_full: false
  },
  {
    uri: '/common/member/4',
    page: Common.Member.Page4,
    type: 'common',
    cate: 'member',
    id: '4',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#4'),
    is_full: false
  },
  {
    uri: '/common/member/5',
    page: Common.Member.Page5,
    type: 'common',
    cate: 'member',
    id: '5',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#5'),
    is_full: false
  },
  {
    uri: '/common/member/6',
    page: Common.Member.Page6,
    type: 'common',
    cate: 'member',
    id: '6',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#6'),
    is_full: false
  },
  {
    uri: '/common/member/7',
    page: Common.Member.Page7,
    type: 'common',
    cate: 'member',
    id: '7',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#7'),
    is_full: false
  },
  {
    uri: '/common/member/8',
    page: Common.Member.Page8,
    type: 'common',
    cate: 'member',
    id: '8',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#8'),
    is_full: false
  },
  {
    uri: '/common/member/9',
    page: Common.Member.Page9,
    type: 'common',
    cate: 'member',
    id: '9',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#9'),
    is_full: false
  },
  {
    uri: '/common/member/10',
    page: Common.Member.Page10,
    type: 'common',
    cate: 'member',
    id: '10',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/member/11',
    page: Common.Member.Page11,
    type: 'common',
    cate: 'member',
    id: '11',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/member/12',
    page: Common.Member.Page12,
    type: 'common',
    cate: 'member',
    id: '12',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/member/13',
    page: Common.Member.Page13,
    type: 'common',
    cate: 'member',
    id: '13',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/member/14',
    page: Common.Member.Page14,
    type: 'common',
    cate: 'member',
    id: '14',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/member/15',
    page: Common.Member.Page15,
    type: 'common',
    cate: 'member',
    id: '15',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/member/16',
    page: Common.Member.Page16,
    type: 'common',
    cate: 'member',
    id: '16',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/member/17',
    page: Common.Member.Page17,
    type: 'common',
    cate: 'member',
    id: '17',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/member/18',
    page: Common.Member.Page18,
    type: 'common',
    cate: 'member',
    id: '18',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/member/19',
    page: Common.Member.Page19,
    type: 'common',
    cate: 'member',
    id: '19',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/member/20',
    page: Common.Member.Page20,
    type: 'common',
    cate: 'member',
    id: '20',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/member/21',
    page: Common.Member.Page21,
    type: 'common',
    cate: 'member',
    id: '21',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/member/22',
    page: Common.Member.Page22,
    type: 'common',
    cate: 'member',
    id: '22',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/member/23',
    page: Common.Member.Page23,
    type: 'common',
    cate: 'member',
    id: '23',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/member/24',
    page: Common.Member.Page24,
    type: 'common',
    cate: 'member',
    id: '24',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/member/25',
    page: Common.Member.Page25,
    type: 'common',
    cate: 'member',
    id: '25',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/member/26',
    page: Common.Member.Page26,
    type: 'common',
    cate: 'member',
    id: '26',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/member/27',
    page: Common.Member.Page27,
    type: 'common',
    cate: 'member',
    id: '27',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/member/28',
    page: Common.Member.Page28,
    type: 'common',
    cate: 'member',
    id: '28',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/member/29',
    page: Common.Member.Page29,
    type: 'common',
    cate: 'member',
    id: '29',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/member/30',
    page: Common.Member.Page30,
    type: 'common',
    cate: 'member',
    id: '30',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('회원관리'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },
  {
    uri: '/common/group/0',
    type: 'common',
    cate: 'group',
    id: '0',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#0'),
    page: Common.Group.Page0,
    is_full: false
  },
  {
    uri: '/common/group/1',
    page: Common.Group.Page1,
    type: 'common',
    cate: 'group',
    id: '1',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#1'),
    is_full: false
  },
  {
    uri: '/common/group/2',
    page: Common.Group.Page2,
    type: 'common',
    cate: 'group',
    id: '2',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#2'),
    is_full: false
  },
  {
    uri: '/common/group/3',
    page: Common.Group.Page3,
    type: 'common',
    cate: 'group',
    id: '3',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#3'),
    is_full: false
  },
  {
    uri: '/common/group/4',
    page: Common.Group.Page4,
    type: 'common',
    cate: 'group',
    id: '4',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#4'),
    is_full: false
  },
  {
    uri: '/common/group/5',
    page: Common.Group.Page5,
    type: 'common',
    cate: 'group',
    id: '5',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#5'),
    is_full: false
  },
  {
    uri: '/common/group/6',
    page: Common.Group.Page6,
    type: 'common',
    cate: 'group',
    id: '6',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#6'),
    is_full: false
  },
  {
    uri: '/common/group/7',
    page: Common.Group.Page7,
    type: 'common',
    cate: 'group',
    id: '7',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#7'),
    is_full: false
  },
  {
    uri: '/common/group/8',
    page: Common.Group.Page8,
    type: 'common',
    cate: 'group',
    id: '8',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#8'),
    is_full: false
  },
  {
    uri: '/common/group/9',
    page: Common.Group.Page9,
    type: 'common',
    cate: 'group',
    id: '9',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#9'),
    is_full: false
  },
  {
    uri: '/common/group/10',
    page: Common.Group.Page10,
    type: 'common',
    cate: 'group',
    id: '10',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/group/11',
    page: Common.Group.Page11,
    type: 'common',
    cate: 'group',
    id: '11',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/group/12',
    page: Common.Group.Page12,
    type: 'common',
    cate: 'group',
    id: '12',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/group/13',
    page: Common.Group.Page13,
    type: 'common',
    cate: 'group',
    id: '13',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/group/14',
    page: Common.Group.Page14,
    type: 'common',
    cate: 'group',
    id: '14',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/group/15',
    page: Common.Group.Page15,
    type: 'common',
    cate: 'group',
    id: '15',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/group/16',
    page: Common.Group.Page16,
    type: 'common',
    cate: 'group',
    id: '16',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/group/17',
    page: Common.Group.Page17,
    type: 'common',
    cate: 'group',
    id: '17',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/group/18',
    page: Common.Group.Page18,
    type: 'common',
    cate: 'group',
    id: '18',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/group/19',
    page: Common.Group.Page19,
    type: 'common',
    cate: 'group',
    id: '19',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/group/20',
    page: Common.Group.Page20,
    type: 'common',
    cate: 'group',
    id: '20',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/group/21',
    page: Common.Group.Page21,
    type: 'common',
    cate: 'group',
    id: '21',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/group/22',
    page: Common.Group.Page22,
    type: 'common',
    cate: 'group',
    id: '22',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/group/23',
    page: Common.Group.Page23,
    type: 'common',
    cate: 'group',
    id: '23',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/group/24',
    page: Common.Group.Page24,
    type: 'common',
    cate: 'group',
    id: '24',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/group/25',
    page: Common.Group.Page25,
    type: 'common',
    cate: 'group',
    id: '25',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/group/26',
    page: Common.Group.Page26,
    type: 'common',
    cate: 'group',
    id: '26',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/group/27',
    page: Common.Group.Page27,
    type: 'common',
    cate: 'group',
    id: '27',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/group/28',
    page: Common.Group.Page28,
    type: 'common',
    cate: 'group',
    id: '28',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/group/29',
    page: Common.Group.Page29,
    type: 'common',
    cate: 'group',
    id: '29',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/group/30',
    page: Common.Group.Page30,
    type: 'common',
    cate: 'group',
    id: '30',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('그룹관리'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },
  {
    uri: '/common/roll/0',
    type: 'common',
    cate: 'roll',
    id: '0',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#0'),
    page: Common.Roll.Page0,
    is_full: false
  },
  {
    uri: '/common/roll/1',
    page: Common.Roll.Page1,
    type: 'common',
    cate: 'roll',
    id: '1',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#1'),
    is_full: false
  },
  {
    uri: '/common/roll/2',
    page: Common.Roll.Page2,
    type: 'common',
    cate: 'roll',
    id: '2',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#2'),
    is_full: false
  },
  {
    uri: '/common/roll/3',
    page: Common.Roll.Page3,
    type: 'common',
    cate: 'roll',
    id: '3',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#3'),
    is_full: false
  },
  {
    uri: '/common/roll/4',
    page: Common.Roll.Page4,
    type: 'common',
    cate: 'roll',
    id: '4',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#4'),
    is_full: false
  },
  {
    uri: '/common/roll/5',
    page: Common.Roll.Page5,
    type: 'common',
    cate: 'roll',
    id: '5',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#5'),
    is_full: false
  },
  {
    uri: '/common/roll/6',
    page: Common.Roll.Page6,
    type: 'common',
    cate: 'roll',
    id: '6',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#6'),
    is_full: false
  },
  {
    uri: '/common/roll/7',
    page: Common.Roll.Page7,
    type: 'common',
    cate: 'roll',
    id: '7',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#7'),
    is_full: false
  },
  {
    uri: '/common/roll/8',
    page: Common.Roll.Page8,
    type: 'common',
    cate: 'roll',
    id: '8',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#8'),
    is_full: false
  },
  {
    uri: '/common/roll/9',
    page: Common.Roll.Page9,
    type: 'common',
    cate: 'roll',
    id: '9',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#9'),
    is_full: false
  },
  {
    uri: '/common/roll/10',
    page: Common.Roll.Page10,
    type: 'common',
    cate: 'roll',
    id: '10',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/roll/11',
    page: Common.Roll.Page11,
    type: 'common',
    cate: 'roll',
    id: '11',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/roll/12',
    page: Common.Roll.Page12,
    type: 'common',
    cate: 'roll',
    id: '12',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/roll/13',
    page: Common.Roll.Page13,
    type: 'common',
    cate: 'roll',
    id: '13',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/roll/14',
    page: Common.Roll.Page14,
    type: 'common',
    cate: 'roll',
    id: '14',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/roll/15',
    page: Common.Roll.Page15,
    type: 'common',
    cate: 'roll',
    id: '15',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/roll/16',
    page: Common.Roll.Page16,
    type: 'common',
    cate: 'roll',
    id: '16',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/roll/17',
    page: Common.Roll.Page17,
    type: 'common',
    cate: 'roll',
    id: '17',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/roll/18',
    page: Common.Roll.Page18,
    type: 'common',
    cate: 'roll',
    id: '18',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/roll/19',
    page: Common.Roll.Page19,
    type: 'common',
    cate: 'roll',
    id: '19',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/roll/20',
    page: Common.Roll.Page20,
    type: 'common',
    cate: 'roll',
    id: '20',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/roll/21',
    page: Common.Roll.Page21,
    type: 'common',
    cate: 'roll',
    id: '21',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/roll/22',
    page: Common.Roll.Page22,
    type: 'common',
    cate: 'roll',
    id: '22',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/roll/23',
    page: Common.Roll.Page23,
    type: 'common',
    cate: 'roll',
    id: '23',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/roll/24',
    page: Common.Roll.Page24,
    type: 'common',
    cate: 'roll',
    id: '24',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/roll/25',
    page: Common.Roll.Page25,
    type: 'common',
    cate: 'roll',
    id: '25',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/roll/26',
    page: Common.Roll.Page26,
    type: 'common',
    cate: 'roll',
    id: '26',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/roll/27',
    page: Common.Roll.Page27,
    type: 'common',
    cate: 'roll',
    id: '27',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/roll/28',
    page: Common.Roll.Page28,
    type: 'common',
    cate: 'roll',
    id: '28',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/roll/29',
    page: Common.Roll.Page29,
    type: 'common',
    cate: 'roll',
    id: '29',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/roll/30',
    page: Common.Roll.Page30,
    type: 'common',
    cate: 'roll',
    id: '30',
    type_nm: i18n.t('공통'),
    cate_nm: i18n.t('권한관리'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  }
];

export default CommonRouteList;
