import * as Common from 'containers/pages/common';
import i18n from 'i18next';

export const CommonRouteList = [
  {
    uri: '/common/member/00',
    page: Common.Member.Page00,
    type: 'common',
    cate: 'member',
    id: '00',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#00'),
    is_full: false
  },
  {
    uri: '/common/member/01',
    page: Common.Member.Page01,
    type: 'common',
    cate: 'member',
    id: '01',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#01'),
    is_full: false
  },
  {
    uri: '/common/member/02',
    page: Common.Member.Page02,
    type: 'common',
    cate: 'member',
    id: '02',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#02'),
    is_full: false
  },
  {
    uri: '/common/member/03',
    page: Common.Member.Page03,
    type: 'common',
    cate: 'member',
    id: '03',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#03'),
    is_full: false
  },
  {
    uri: '/common/member/04',
    page: Common.Member.Page04,
    type: 'common',
    cate: 'member',
    id: '04',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#04'),
    is_full: false
  },
  {
    uri: '/common/member/05',
    page: Common.Member.Page05,
    type: 'common',
    cate: 'member',
    id: '05',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#05'),
    is_full: false
  },
  {
    uri: '/common/member/06',
    page: Common.Member.Page06,
    type: 'common',
    cate: 'member',
    id: '06',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#06'),
    is_full: false
  },
  {
    uri: '/common/member/07',
    page: Common.Member.Page07,
    type: 'common',
    cate: 'member',
    id: '07',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#07'),
    is_full: false
  },
  {
    uri: '/common/member/08',
    page: Common.Member.Page08,
    type: 'common',
    cate: 'member',
    id: '08',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#08'),
    is_full: false
  },
  {
    uri: '/common/member/09',
    page: Common.Member.Page09,
    type: 'common',
    cate: 'member',
    id: '09',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#09'),
    is_full: false
  },
  {
    uri: '/common/member/10',
    page: Common.Member.Page10,
    type: 'common',
    cate: 'member',
    id: '10',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/member/11',
    page: Common.Member.Page11,
    type: 'common',
    cate: 'member',
    id: '11',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/member/12',
    page: Common.Member.Page12,
    type: 'common',
    cate: 'member',
    id: '12',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/member/13',
    page: Common.Member.Page13,
    type: 'common',
    cate: 'member',
    id: '13',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/member/14',
    page: Common.Member.Page14,
    type: 'common',
    cate: 'member',
    id: '14',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/member/15',
    page: Common.Member.Page15,
    type: 'common',
    cate: 'member',
    id: '15',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/member/16',
    page: Common.Member.Page16,
    type: 'common',
    cate: 'member',
    id: '16',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/member/17',
    page: Common.Member.Page17,
    type: 'common',
    cate: 'member',
    id: '17',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/member/18',
    page: Common.Member.Page18,
    type: 'common',
    cate: 'member',
    id: '18',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/member/19',
    page: Common.Member.Page19,
    type: 'common',
    cate: 'member',
    id: '19',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/member/20',
    page: Common.Member.Page20,
    type: 'common',
    cate: 'member',
    id: '20',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/member/21',
    page: Common.Member.Page21,
    type: 'common',
    cate: 'member',
    id: '21',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/member/22',
    page: Common.Member.Page22,
    type: 'common',
    cate: 'member',
    id: '22',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/member/23',
    page: Common.Member.Page23,
    type: 'common',
    cate: 'member',
    id: '23',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/member/24',
    page: Common.Member.Page24,
    type: 'common',
    cate: 'member',
    id: '24',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/member/25',
    page: Common.Member.Page25,
    type: 'common',
    cate: 'member',
    id: '25',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/member/26',
    page: Common.Member.Page26,
    type: 'common',
    cate: 'member',
    id: '26',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/member/27',
    page: Common.Member.Page27,
    type: 'common',
    cate: 'member',
    id: '27',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/member/28',
    page: Common.Member.Page28,
    type: 'common',
    cate: 'member',
    id: '28',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/member/29',
    page: Common.Member.Page29,
    type: 'common',
    cate: 'member',
    id: '29',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/member/30',
    page: Common.Member.Page30,
    type: 'common',
    cate: 'member',
    id: '30',
    type_nm: i18n('공통'),
    cate_nm: i18n('회원관리'),
    page_nm: i18n('페이지#30'),
    is_full: false
  },
  {
    uri: '/common/group/00',
    type: 'common',
    cate: 'group',
    id: '00',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#00'),
    page: Common.Group.Page00,
    is_full: false
  },
  {
    uri: '/common/group/01',
    page: Common.Group.Page01,
    type: 'common',
    cate: 'group',
    id: '01',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#01'),
    is_full: false
  },
  {
    uri: '/common/group/02',
    page: Common.Group.Page02,
    type: 'common',
    cate: 'group',
    id: '02',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#02'),
    is_full: false
  },
  {
    uri: '/common/group/03',
    page: Common.Group.Page03,
    type: 'common',
    cate: 'group',
    id: '03',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#03'),
    is_full: false
  },
  {
    uri: '/common/group/04',
    page: Common.Group.Page04,
    type: 'common',
    cate: 'group',
    id: '04',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#04'),
    is_full: false
  },
  {
    uri: '/common/group/05',
    page: Common.Group.Page05,
    type: 'common',
    cate: 'group',
    id: '05',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#05'),
    is_full: false
  },
  {
    uri: '/common/group/06',
    page: Common.Group.Page06,
    type: 'common',
    cate: 'group',
    id: '06',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#06'),
    is_full: false
  },
  {
    uri: '/common/group/07',
    page: Common.Group.Page07,
    type: 'common',
    cate: 'group',
    id: '07',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#07'),
    is_full: false
  },
  {
    uri: '/common/group/08',
    page: Common.Group.Page08,
    type: 'common',
    cate: 'group',
    id: '08',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#08'),
    is_full: false
  },
  {
    uri: '/common/group/09',
    page: Common.Group.Page09,
    type: 'common',
    cate: 'group',
    id: '09',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#09'),
    is_full: false
  },
  {
    uri: '/common/group/10',
    page: Common.Group.Page10,
    type: 'common',
    cate: 'group',
    id: '10',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/group/11',
    page: Common.Group.Page11,
    type: 'common',
    cate: 'group',
    id: '11',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/group/12',
    page: Common.Group.Page12,
    type: 'common',
    cate: 'group',
    id: '12',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/group/13',
    page: Common.Group.Page13,
    type: 'common',
    cate: 'group',
    id: '13',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/group/14',
    page: Common.Group.Page14,
    type: 'common',
    cate: 'group',
    id: '14',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/group/15',
    page: Common.Group.Page15,
    type: 'common',
    cate: 'group',
    id: '15',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/group/16',
    page: Common.Group.Page16,
    type: 'common',
    cate: 'group',
    id: '16',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/group/17',
    page: Common.Group.Page17,
    type: 'common',
    cate: 'group',
    id: '17',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/group/18',
    page: Common.Group.Page18,
    type: 'common',
    cate: 'group',
    id: '18',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/group/19',
    page: Common.Group.Page19,
    type: 'common',
    cate: 'group',
    id: '19',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/group/20',
    page: Common.Group.Page20,
    type: 'common',
    cate: 'group',
    id: '20',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/group/21',
    page: Common.Group.Page21,
    type: 'common',
    cate: 'group',
    id: '21',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/group/22',
    page: Common.Group.Page22,
    type: 'common',
    cate: 'group',
    id: '22',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/group/23',
    page: Common.Group.Page23,
    type: 'common',
    cate: 'group',
    id: '23',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/group/24',
    page: Common.Group.Page24,
    type: 'common',
    cate: 'group',
    id: '24',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/group/25',
    page: Common.Group.Page25,
    type: 'common',
    cate: 'group',
    id: '25',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/group/26',
    page: Common.Group.Page26,
    type: 'common',
    cate: 'group',
    id: '26',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/group/27',
    page: Common.Group.Page27,
    type: 'common',
    cate: 'group',
    id: '27',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/group/28',
    page: Common.Group.Page28,
    type: 'common',
    cate: 'group',
    id: '28',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/group/29',
    page: Common.Group.Page29,
    type: 'common',
    cate: 'group',
    id: '29',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/group/30',
    page: Common.Group.Page30,
    type: 'common',
    cate: 'group',
    id: '30',
    type_nm: i18n('공통'),
    cate_nm: i18n('그룹관리'),
    page_nm: i18n('페이지#30'),
    is_full: false
  },
  {
    uri: '/common/roll/00',
    type: 'common',
    cate: 'roll',
    id: '00',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#00'),
    page: Common.Roll.Page00,
    is_full: false
  },
  {
    uri: '/common/roll/01',
    page: Common.Roll.Page01,
    type: 'common',
    cate: 'roll',
    id: '01',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#01'),
    is_full: false
  },
  {
    uri: '/common/roll/02',
    page: Common.Roll.Page02,
    type: 'common',
    cate: 'roll',
    id: '02',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#02'),
    is_full: false
  },
  {
    uri: '/common/roll/03',
    page: Common.Roll.Page03,
    type: 'common',
    cate: 'roll',
    id: '03',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#03'),
    is_full: false
  },
  {
    uri: '/common/roll/04',
    page: Common.Roll.Page04,
    type: 'common',
    cate: 'roll',
    id: '04',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#04'),
    is_full: false
  },
  {
    uri: '/common/roll/05',
    page: Common.Roll.Page05,
    type: 'common',
    cate: 'roll',
    id: '05',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#05'),
    is_full: false
  },
  {
    uri: '/common/roll/06',
    page: Common.Roll.Page06,
    type: 'common',
    cate: 'roll',
    id: '06',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#06'),
    is_full: false
  },
  {
    uri: '/common/roll/07',
    page: Common.Roll.Page07,
    type: 'common',
    cate: 'roll',
    id: '07',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#07'),
    is_full: false
  },
  {
    uri: '/common/roll/08',
    page: Common.Roll.Page08,
    type: 'common',
    cate: 'roll',
    id: '08',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#08'),
    is_full: false
  },
  {
    uri: '/common/roll/09',
    page: Common.Roll.Page09,
    type: 'common',
    cate: 'roll',
    id: '09',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#09'),
    is_full: false
  },
  {
    uri: '/common/roll/10',
    page: Common.Roll.Page10,
    type: 'common',
    cate: 'roll',
    id: '10',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#10'),
    is_full: false
  },
  {
    uri: '/common/roll/11',
    page: Common.Roll.Page11,
    type: 'common',
    cate: 'roll',
    id: '11',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#11'),
    is_full: false
  },
  {
    uri: '/common/roll/12',
    page: Common.Roll.Page12,
    type: 'common',
    cate: 'roll',
    id: '12',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#12'),
    is_full: false
  },
  {
    uri: '/common/roll/13',
    page: Common.Roll.Page13,
    type: 'common',
    cate: 'roll',
    id: '13',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#13'),
    is_full: false
  },
  {
    uri: '/common/roll/14',
    page: Common.Roll.Page14,
    type: 'common',
    cate: 'roll',
    id: '14',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#14'),
    is_full: false
  },
  {
    uri: '/common/roll/15',
    page: Common.Roll.Page15,
    type: 'common',
    cate: 'roll',
    id: '15',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#15'),
    is_full: false
  },
  {
    uri: '/common/roll/16',
    page: Common.Roll.Page16,
    type: 'common',
    cate: 'roll',
    id: '16',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#16'),
    is_full: false
  },
  {
    uri: '/common/roll/17',
    page: Common.Roll.Page17,
    type: 'common',
    cate: 'roll',
    id: '17',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#17'),
    is_full: false
  },
  {
    uri: '/common/roll/18',
    page: Common.Roll.Page18,
    type: 'common',
    cate: 'roll',
    id: '18',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#18'),
    is_full: false
  },
  {
    uri: '/common/roll/19',
    page: Common.Roll.Page19,
    type: 'common',
    cate: 'roll',
    id: '19',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#19'),
    is_full: false
  },
  {
    uri: '/common/roll/20',
    page: Common.Roll.Page20,
    type: 'common',
    cate: 'roll',
    id: '20',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#20'),
    is_full: false
  },
  {
    uri: '/common/roll/21',
    page: Common.Roll.Page21,
    type: 'common',
    cate: 'roll',
    id: '21',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#21'),
    is_full: false
  },
  {
    uri: '/common/roll/22',
    page: Common.Roll.Page22,
    type: 'common',
    cate: 'roll',
    id: '22',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#22'),
    is_full: false
  },
  {
    uri: '/common/roll/23',
    page: Common.Roll.Page23,
    type: 'common',
    cate: 'roll',
    id: '23',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#23'),
    is_full: false
  },
  {
    uri: '/common/roll/24',
    page: Common.Roll.Page24,
    type: 'common',
    cate: 'roll',
    id: '24',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#24'),
    is_full: false
  },
  {
    uri: '/common/roll/25',
    page: Common.Roll.Page25,
    type: 'common',
    cate: 'roll',
    id: '25',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#25'),
    is_full: false
  },
  {
    uri: '/common/roll/26',
    page: Common.Roll.Page26,
    type: 'common',
    cate: 'roll',
    id: '26',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#26'),
    is_full: false
  },
  {
    uri: '/common/roll/27',
    page: Common.Roll.Page27,
    type: 'common',
    cate: 'roll',
    id: '27',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#27'),
    is_full: false
  },
  {
    uri: '/common/roll/28',
    page: Common.Roll.Page28,
    type: 'common',
    cate: 'roll',
    id: '28',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#28'),
    is_full: false
  },
  {
    uri: '/common/roll/29',
    page: Common.Roll.Page29,
    type: 'common',
    cate: 'roll',
    id: '29',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#29'),
    is_full: false
  },
  {
    uri: '/common/roll/30',
    page: Common.Roll.Page30,
    type: 'common',
    cate: 'roll',
    id: '30',
    type_nm: i18n('공통'),
    cate_nm: i18n('권한관리'),
    page_nm: i18n('페이지#30'),
    is_full: false
  }
];
