import * as Hatchery from 'containers/pages/hatchery';
import i18n from 'i18next';

export const HatcheryRouteList = [
  {
    uri: '/hatchery/receive/00',
    page: Hatchery.Receive.Page00,
    type: 'hatchery',
    cate: 'receive',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/01',
    page: Hatchery.Receive.Page01,
    type: 'hatchery',
    cate: 'receive',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/02',
    page: Hatchery.Receive.Page02,
    type: 'hatchery',
    cate: 'receive',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/03',
    page: Hatchery.Receive.Page03,
    type: 'hatchery',
    cate: 'receive',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/04',
    page: Hatchery.Receive.Page04,
    type: 'hatchery',
    cate: 'receive',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/05',
    page: Hatchery.Receive.Page05,
    type: 'hatchery',
    cate: 'receive',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/06',
    page: Hatchery.Receive.Page06,
    type: 'hatchery',
    cate: 'receive',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/07',
    page: Hatchery.Receive.Page07,
    type: 'hatchery',
    cate: 'receive',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/08',
    page: Hatchery.Receive.Page08,
    type: 'hatchery',
    cate: 'receive',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/09',
    page: Hatchery.Receive.Page09,
    type: 'hatchery',
    cate: 'receive',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/10',
    page: Hatchery.Receive.Page10,
    type: 'hatchery',
    cate: 'receive',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/11',
    page: Hatchery.Receive.Page11,
    type: 'hatchery',
    cate: 'receive',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/12',
    page: Hatchery.Receive.Page12,
    type: 'hatchery',
    cate: 'receive',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/13',
    page: Hatchery.Receive.Page13,
    type: 'hatchery',
    cate: 'receive',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/14',
    page: Hatchery.Receive.Page14,
    type: 'hatchery',
    cate: 'receive',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/15',
    page: Hatchery.Receive.Page15,
    type: 'hatchery',
    cate: 'receive',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/16',
    page: Hatchery.Receive.Page16,
    type: 'hatchery',
    cate: 'receive',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/17',
    page: Hatchery.Receive.Page17,
    type: 'hatchery',
    cate: 'receive',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/18',
    page: Hatchery.Receive.Page18,
    type: 'hatchery',
    cate: 'receive',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/19',
    page: Hatchery.Receive.Page19,
    type: 'hatchery',
    cate: 'receive',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/20',
    page: Hatchery.Receive.Page20,
    type: 'hatchery',
    cate: 'receive',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/21',
    page: Hatchery.Receive.Page21,
    type: 'hatchery',
    cate: 'receive',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/22',
    page: Hatchery.Receive.Page22,
    type: 'hatchery',
    cate: 'receive',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/23',
    page: Hatchery.Receive.Page23,
    type: 'hatchery',
    cate: 'receive',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/24',
    page: Hatchery.Receive.Page24,
    type: 'hatchery',
    cate: 'receive',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/25',
    page: Hatchery.Receive.Page25,
    type: 'hatchery',
    cate: 'receive',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/26',
    page: Hatchery.Receive.Page26,
    type: 'hatchery',
    cate: 'receive',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/27',
    page: Hatchery.Receive.Page27,
    type: 'hatchery',
    cate: 'receive',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/28',
    page: Hatchery.Receive.Page28,
    type: 'hatchery',
    cate: 'receive',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/29',
    page: Hatchery.Receive.Page29,
    type: 'hatchery',
    cate: 'receive',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/receive/30',
    page: Hatchery.Receive.Page30,
    type: 'hatchery',
    cate: 'receive',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/candling/00',
    page: Hatchery.Candling.Page00,
    type: 'hatchery',
    cate: 'candling',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/01',
    page: Hatchery.Candling.Page01,
    type: 'hatchery',
    cate: 'candling',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/02',
    page: Hatchery.Candling.Page02,
    type: 'hatchery',
    cate: 'candling',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/03',
    page: Hatchery.Candling.Page03,
    type: 'hatchery',
    cate: 'candling',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/04',
    page: Hatchery.Candling.Page04,
    type: 'hatchery',
    cate: 'candling',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/05',
    page: Hatchery.Candling.Page05,
    type: 'hatchery',
    cate: 'candling',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/06',
    page: Hatchery.Candling.Page06,
    type: 'hatchery',
    cate: 'candling',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/07',
    page: Hatchery.Candling.Page07,
    type: 'hatchery',
    cate: 'candling',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/08',
    page: Hatchery.Candling.Page08,
    type: 'hatchery',
    cate: 'candling',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/09',
    page: Hatchery.Candling.Page09,
    type: 'hatchery',
    cate: 'candling',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/10',
    page: Hatchery.Candling.Page10,
    type: 'hatchery',
    cate: 'candling',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/11',
    page: Hatchery.Candling.Page11,
    type: 'hatchery',
    cate: 'candling',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/00',
    page: Hatchery.Candling.Page00,
    type: 'hatchery',
    cate: 'candling',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/01',
    page: Hatchery.Candling.Page01,
    type: 'hatchery',
    cate: 'candling',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/02',
    page: Hatchery.Candling.Page02,
    type: 'hatchery',
    cate: 'candling',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/03',
    page: Hatchery.Candling.Page03,
    type: 'hatchery',
    cate: 'candling',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/04',
    page: Hatchery.Candling.Page04,
    type: 'hatchery',
    cate: 'candling',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/05',
    page: Hatchery.Candling.Page05,
    type: 'hatchery',
    cate: 'candling',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/06',
    page: Hatchery.Candling.Page06,
    type: 'hatchery',
    cate: 'candling',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/07',
    page: Hatchery.Candling.Page07,
    type: 'hatchery',
    cate: 'candling',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/08',
    page: Hatchery.Candling.Page08,
    type: 'hatchery',
    cate: 'candling',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/09',
    page: Hatchery.Candling.Page09,
    type: 'hatchery',
    cate: 'candling',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/10',
    page: Hatchery.Candling.Page10,
    type: 'hatchery',
    cate: 'candling',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/11',
    page: Hatchery.Candling.Page11,
    type: 'hatchery',
    cate: 'candling',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/12',
    page: Hatchery.Candling.Page12,
    type: 'hatchery',
    cate: 'candling',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/13',
    page: Hatchery.Candling.Page13,
    type: 'hatchery',
    cate: 'candling',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/14',
    page: Hatchery.Candling.Page14,
    type: 'hatchery',
    cate: 'candling',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/15',
    page: Hatchery.Candling.Page15,
    type: 'hatchery',
    cate: 'candling',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/16',
    page: Hatchery.Candling.Page16,
    type: 'hatchery',
    cate: 'candling',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/17',
    page: Hatchery.Candling.Page17,
    type: 'hatchery',
    cate: 'candling',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/18',
    page: Hatchery.Candling.Page18,
    type: 'hatchery',
    cate: 'candling',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/19',
    page: Hatchery.Candling.Page19,
    type: 'hatchery',
    cate: 'candling',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/20',
    page: Hatchery.Candling.Page20,
    type: 'hatchery',
    cate: 'candling',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/21',
    page: Hatchery.Candling.Page21,
    type: 'hatchery',
    cate: 'candling',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/22',
    page: Hatchery.Candling.Page22,
    type: 'hatchery',
    cate: 'candling',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/23',
    page: Hatchery.Candling.Page23,
    type: 'hatchery',
    cate: 'candling',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/24',
    page: Hatchery.Candling.Page24,
    type: 'hatchery',
    cate: 'candling',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/25',
    page: Hatchery.Candling.Page25,
    type: 'hatchery',
    cate: 'candling',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/26',
    page: Hatchery.Candling.Page26,
    type: 'hatchery',
    cate: 'candling',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/27',
    page: Hatchery.Candling.Page27,
    type: 'hatchery',
    cate: 'candling',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/28',
    page: Hatchery.Candling.Page28,
    type: 'hatchery',
    cate: 'candling',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/29',
    page: Hatchery.Candling.Page29,
    type: 'hatchery',
    cate: 'candling',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/30',
    page: Hatchery.Candling.Page30,
    type: 'hatchery',
    cate: 'candling',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/hatcher/00',
    page: Hatchery.Hatcher.Page00,
    type: 'hatchery',
    cate: 'hatcher',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/01',
    page: Hatchery.Hatcher.Page01,
    type: 'hatchery',
    cate: 'hatcher',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/02',
    page: Hatchery.Hatcher.Page02,
    type: 'hatchery',
    cate: 'hatcher',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/03',
    page: Hatchery.Hatcher.Page03,
    type: 'hatchery',
    cate: 'hatcher',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/04',
    page: Hatchery.Hatcher.Page04,
    type: 'hatchery',
    cate: 'hatcher',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/05',
    page: Hatchery.Hatcher.Page05,
    type: 'hatchery',
    cate: 'hatcher',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/06',
    page: Hatchery.Hatcher.Page06,
    type: 'hatchery',
    cate: 'hatcher',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/07',
    page: Hatchery.Hatcher.Page07,
    type: 'hatchery',
    cate: 'hatcher',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/08',
    page: Hatchery.Hatcher.Page08,
    type: 'hatchery',
    cate: 'hatcher',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/09',
    page: Hatchery.Hatcher.Page09,
    type: 'hatchery',
    cate: 'hatcher',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/10',
    page: Hatchery.Hatcher.Page10,
    type: 'hatchery',
    cate: 'hatcher',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/11',
    page: Hatchery.Hatcher.Page11,
    type: 'hatchery',
    cate: 'hatcher',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/12',
    page: Hatchery.Hatcher.Page12,
    type: 'hatchery',
    cate: 'hatcher',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/13',
    page: Hatchery.Hatcher.Page13,
    type: 'hatchery',
    cate: 'hatcher',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/14',
    page: Hatchery.Hatcher.Page14,
    type: 'hatchery',
    cate: 'hatcher',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/15',
    page: Hatchery.Hatcher.Page15,
    type: 'hatchery',
    cate: 'hatcher',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/16',
    page: Hatchery.Hatcher.Page16,
    type: 'hatchery',
    cate: 'hatcher',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/17',
    page: Hatchery.Hatcher.Page17,
    type: 'hatchery',
    cate: 'hatcher',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/18',
    page: Hatchery.Hatcher.Page18,
    type: 'hatchery',
    cate: 'hatcher',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/19',
    page: Hatchery.Hatcher.Page19,
    type: 'hatchery',
    cate: 'hatcher',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/20',
    page: Hatchery.Hatcher.Page20,
    type: 'hatchery',
    cate: 'hatcher',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/21',
    page: Hatchery.Hatcher.Page21,
    type: 'hatchery',
    cate: 'hatcher',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/22',
    page: Hatchery.Hatcher.Page22,
    type: 'hatchery',
    cate: 'hatcher',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/23',
    page: Hatchery.Hatcher.Page23,
    type: 'hatchery',
    cate: 'hatcher',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/24',
    page: Hatchery.Hatcher.Page24,
    type: 'hatchery',
    cate: 'hatcher',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/25',
    page: Hatchery.Hatcher.Page25,
    type: 'hatchery',
    cate: 'hatcher',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/26',
    page: Hatchery.Hatcher.Page26,
    type: 'hatchery',
    cate: 'hatcher',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/27',
    page: Hatchery.Hatcher.Page27,
    type: 'hatchery',
    cate: 'hatcher',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/28',
    page: Hatchery.Hatcher.Page28,
    type: 'hatchery',
    cate: 'hatcher',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/29',
    page: Hatchery.Hatcher.Page29,
    type: 'hatchery',
    cate: 'hatcher',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/30',
    page: Hatchery.Hatcher.Page30,
    type: 'hatchery',
    cate: 'hatcher',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },

  {
    uri: '/hatchery/cutting/00',
    page: Hatchery.Cutting.Page00,
    type: 'hatchery',
    cate: 'cutting',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/01',
    page: Hatchery.Cutting.Page01,
    type: 'hatchery',
    cate: 'cutting',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/02',
    page: Hatchery.Cutting.Page02,
    type: 'hatchery',
    cate: 'cutting',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/03',
    page: Hatchery.Cutting.Page03,
    type: 'hatchery',
    cate: 'cutting',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/04',
    page: Hatchery.Cutting.Page04,
    type: 'hatchery',
    cate: 'cutting',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/05',
    page: Hatchery.Cutting.Page05,
    type: 'hatchery',
    cate: 'cutting',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/06',
    page: Hatchery.Cutting.Page06,
    type: 'hatchery',
    cate: 'cutting',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/07',
    page: Hatchery.Cutting.Page07,
    type: 'hatchery',
    cate: 'cutting',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/08',
    page: Hatchery.Cutting.Page08,
    type: 'hatchery',
    cate: 'cutting',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/09',
    page: Hatchery.Cutting.Page09,
    type: 'hatchery',
    cate: 'cutting',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/10',
    page: Hatchery.Cutting.Page10,
    type: 'hatchery',
    cate: 'cutting',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/11',
    page: Hatchery.Cutting.Page11,
    type: 'hatchery',
    cate: 'cutting',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/12',
    page: Hatchery.Cutting.Page12,
    type: 'hatchery',
    cate: 'cutting',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/13',
    page: Hatchery.Cutting.Page13,
    type: 'hatchery',
    cate: 'cutting',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/14',
    page: Hatchery.Cutting.Page14,
    type: 'hatchery',
    cate: 'cutting',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/15',
    page: Hatchery.Cutting.Page15,
    type: 'hatchery',
    cate: 'cutting',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/16',
    page: Hatchery.Cutting.Page16,
    type: 'hatchery',
    cate: 'cutting',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/17',
    page: Hatchery.Cutting.Page17,
    type: 'hatchery',
    cate: 'cutting',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/18',
    page: Hatchery.Cutting.Page18,
    type: 'hatchery',
    cate: 'cutting',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/19',
    page: Hatchery.Cutting.Page19,
    type: 'hatchery',
    cate: 'cutting',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/20',
    page: Hatchery.Cutting.Page20,
    type: 'hatchery',
    cate: 'cutting',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/21',
    page: Hatchery.Cutting.Page21,
    type: 'hatchery',
    cate: 'cutting',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/22',
    page: Hatchery.Cutting.Page22,
    type: 'hatchery',
    cate: 'cutting',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/23',
    page: Hatchery.Cutting.Page23,
    type: 'hatchery',
    cate: 'cutting',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/24',
    page: Hatchery.Cutting.Page24,
    type: 'hatchery',
    cate: 'cutting',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/25',
    page: Hatchery.Cutting.Page25,
    type: 'hatchery',
    cate: 'cutting',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/26',
    page: Hatchery.Cutting.Page26,
    type: 'hatchery',
    cate: 'cutting',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/27',
    page: Hatchery.Cutting.Page27,
    type: 'hatchery',
    cate: 'cutting',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/28',
    page: Hatchery.Cutting.Page28,
    type: 'hatchery',
    cate: 'cutting',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/29',
    page: Hatchery.Cutting.Page29,
    type: 'hatchery',
    cate: 'cutting',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/30',
    page: Hatchery.Cutting.Page30,
    type: 'hatchery',
    cate: 'cutting',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  }
];
