import * as Hatchery from 'containers/pages/hatchery';
import i18n from 'i18next';

const HatcheryRouteList = [
  {
    uri: '/hatchery/rcvmng/00',
    page: Hatchery.Rcvmng.Page00,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/01',
    page: Hatchery.Rcvmng.Page01,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/02',
    page: Hatchery.Rcvmng.Page02,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/03',
    page: Hatchery.Rcvmng.Page03,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/04',
    page: Hatchery.Rcvmng.Page04,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/05',
    page: Hatchery.Rcvmng.Page05,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/06',
    page: Hatchery.Rcvmng.Page06,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/07',
    page: Hatchery.Rcvmng.Page07,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/08',
    page: Hatchery.Rcvmng.Page08,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/09',
    page: Hatchery.Rcvmng.Page09,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/10',
    page: Hatchery.Rcvmng.Page10,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/11',
    page: Hatchery.Rcvmng.Page11,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/12',
    page: Hatchery.Rcvmng.Page12,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/13',
    page: Hatchery.Rcvmng.Page13,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/14',
    page: Hatchery.Rcvmng.Page14,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/15',
    page: Hatchery.Rcvmng.Page15,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/16',
    page: Hatchery.Rcvmng.Page16,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/17',
    page: Hatchery.Rcvmng.Page17,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/18',
    page: Hatchery.Rcvmng.Page18,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/19',
    page: Hatchery.Rcvmng.Page19,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/20',
    page: Hatchery.Rcvmng.Page20,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/21',
    page: Hatchery.Rcvmng.Page21,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/22',
    page: Hatchery.Rcvmng.Page22,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/23',
    page: Hatchery.Rcvmng.Page23,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/24',
    page: Hatchery.Rcvmng.Page24,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/25',
    page: Hatchery.Rcvmng.Page25,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/26',
    page: Hatchery.Rcvmng.Page26,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/27',
    page: Hatchery.Rcvmng.Page27,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/28',
    page: Hatchery.Rcvmng.Page28,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/29',
    page: Hatchery.Rcvmng.Page29,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvmng/30',
    page: Hatchery.Rcvmng.Page30,
    type: 'hatchery',
    cate: 'rcvmng',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고관리'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/rcvlist/00',
    page: Hatchery.Rcvlist.Page00,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/01',
    page: Hatchery.Rcvlist.Page01,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/02',
    page: Hatchery.Rcvlist.Page02,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/03',
    page: Hatchery.Rcvlist.Page03,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/04',
    page: Hatchery.Rcvlist.Page04,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/05',
    page: Hatchery.Rcvlist.Page05,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/06',
    page: Hatchery.Rcvlist.Page06,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/07',
    page: Hatchery.Rcvlist.Page07,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/08',
    page: Hatchery.Rcvlist.Page08,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/09',
    page: Hatchery.Rcvlist.Page09,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/10',
    page: Hatchery.Rcvlist.Page10,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/11',
    page: Hatchery.Rcvlist.Page11,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/12',
    page: Hatchery.Rcvlist.Page12,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/13',
    page: Hatchery.Rcvlist.Page13,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/14',
    page: Hatchery.Rcvlist.Page14,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/15',
    page: Hatchery.Rcvlist.Page15,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/16',
    page: Hatchery.Rcvlist.Page16,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/17',
    page: Hatchery.Rcvlist.Page17,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/18',
    page: Hatchery.Rcvlist.Page18,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/19',
    page: Hatchery.Rcvlist.Page19,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/20',
    page: Hatchery.Rcvlist.Page20,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/21',
    page: Hatchery.Rcvlist.Page21,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/22',
    page: Hatchery.Rcvlist.Page22,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/23',
    page: Hatchery.Rcvlist.Page23,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/24',
    page: Hatchery.Rcvlist.Page24,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/25',
    page: Hatchery.Rcvlist.Page25,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/26',
    page: Hatchery.Rcvlist.Page26,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/27',
    page: Hatchery.Rcvlist.Page27,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/28',
    page: Hatchery.Rcvlist.Page28,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/29',
    page: Hatchery.Rcvlist.Page29,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/rcvlist/30',
    page: Hatchery.Rcvlist.Page30,
    type: 'hatchery',
    cate: 'rcvlist',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('입고목록/입란'),
    cate_desc: i18n.t('입고된 계란을 등록 수정 검란을 합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/candling/00',
    page: Hatchery.Candling.Page00,
    type: 'hatchery',
    cate: 'candling',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/01',
    page: Hatchery.Candling.Page01,
    type: 'hatchery',
    cate: 'candling',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/02',
    page: Hatchery.Candling.Page02,
    type: 'hatchery',
    cate: 'candling',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/03',
    page: Hatchery.Candling.Page03,
    type: 'hatchery',
    cate: 'candling',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/04',
    page: Hatchery.Candling.Page04,
    type: 'hatchery',
    cate: 'candling',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/05',
    page: Hatchery.Candling.Page05,
    type: 'hatchery',
    cate: 'candling',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/06',
    page: Hatchery.Candling.Page06,
    type: 'hatchery',
    cate: 'candling',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/07',
    page: Hatchery.Candling.Page07,
    type: 'hatchery',
    cate: 'candling',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/08',
    page: Hatchery.Candling.Page08,
    type: 'hatchery',
    cate: 'candling',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/09',
    page: Hatchery.Candling.Page09,
    type: 'hatchery',
    cate: 'candling',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/10',
    page: Hatchery.Candling.Page10,
    type: 'hatchery',
    cate: 'candling',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/11',
    page: Hatchery.Candling.Page11,
    type: 'hatchery',
    cate: 'candling',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/12',
    page: Hatchery.Candling.Page12,
    type: 'hatchery',
    cate: 'candling',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/13',
    page: Hatchery.Candling.Page13,
    type: 'hatchery',
    cate: 'candling',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/14',
    page: Hatchery.Candling.Page14,
    type: 'hatchery',
    cate: 'candling',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/15',
    page: Hatchery.Candling.Page15,
    type: 'hatchery',
    cate: 'candling',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/16',
    page: Hatchery.Candling.Page16,
    type: 'hatchery',
    cate: 'candling',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/17',
    page: Hatchery.Candling.Page17,
    type: 'hatchery',
    cate: 'candling',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/18',
    page: Hatchery.Candling.Page18,
    type: 'hatchery',
    cate: 'candling',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/19',
    page: Hatchery.Candling.Page19,
    type: 'hatchery',
    cate: 'candling',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/20',
    page: Hatchery.Candling.Page20,
    type: 'hatchery',
    cate: 'candling',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/21',
    page: Hatchery.Candling.Page21,
    type: 'hatchery',
    cate: 'candling',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/22',
    page: Hatchery.Candling.Page22,
    type: 'hatchery',
    cate: 'candling',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/23',
    page: Hatchery.Candling.Page23,
    type: 'hatchery',
    cate: 'candling',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/24',
    page: Hatchery.Candling.Page24,
    type: 'hatchery',
    cate: 'candling',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/25',
    page: Hatchery.Candling.Page25,
    type: 'hatchery',
    cate: 'candling',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/26',
    page: Hatchery.Candling.Page26,
    type: 'hatchery',
    cate: 'candling',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/27',
    page: Hatchery.Candling.Page27,
    type: 'hatchery',
    cate: 'candling',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/28',
    page: Hatchery.Candling.Page28,
    type: 'hatchery',
    cate: 'candling',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/29',
    page: Hatchery.Candling.Page29,
    type: 'hatchery',
    cate: 'candling',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/30',
    page: Hatchery.Candling.Page30,
    type: 'hatchery',
    cate: 'candling',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/hatcher/00',
    page: Hatchery.Hatcher.Page00,
    type: 'hatchery',
    cate: 'hatcher',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('해쳐'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/01',
    page: Hatchery.Candling.Page01,
    type: 'hatchery',
    cate: 'candling',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/02',
    page: Hatchery.Candling.Page02,
    type: 'hatchery',
    cate: 'candling',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/03',
    page: Hatchery.Candling.Page03,
    type: 'hatchery',
    cate: 'candling',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/04',
    page: Hatchery.Candling.Page04,
    type: 'hatchery',
    cate: 'candling',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/05',
    page: Hatchery.Candling.Page05,
    type: 'hatchery',
    cate: 'candling',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/06',
    page: Hatchery.Candling.Page06,
    type: 'hatchery',
    cate: 'candling',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/07',
    page: Hatchery.Candling.Page07,
    type: 'hatchery',
    cate: 'candling',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/08',
    page: Hatchery.Candling.Page08,
    type: 'hatchery',
    cate: 'candling',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/09',
    page: Hatchery.Candling.Page09,
    type: 'hatchery',
    cate: 'candling',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/10',
    page: Hatchery.Candling.Page10,
    type: 'hatchery',
    cate: 'candling',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/11',
    page: Hatchery.Candling.Page11,
    type: 'hatchery',
    cate: 'candling',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/12',
    page: Hatchery.Candling.Page12,
    type: 'hatchery',
    cate: 'candling',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/13',
    page: Hatchery.Candling.Page13,
    type: 'hatchery',
    cate: 'candling',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/14',
    page: Hatchery.Candling.Page14,
    type: 'hatchery',
    cate: 'candling',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/15',
    page: Hatchery.Candling.Page15,
    type: 'hatchery',
    cate: 'candling',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/16',
    page: Hatchery.Candling.Page16,
    type: 'hatchery',
    cate: 'candling',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/17',
    page: Hatchery.Candling.Page17,
    type: 'hatchery',
    cate: 'candling',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/18',
    page: Hatchery.Candling.Page18,
    type: 'hatchery',
    cate: 'candling',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/19',
    page: Hatchery.Candling.Page19,
    type: 'hatchery',
    cate: 'candling',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/20',
    page: Hatchery.Candling.Page20,
    type: 'hatchery',
    cate: 'candling',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/21',
    page: Hatchery.Candling.Page21,
    type: 'hatchery',
    cate: 'candling',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/22',
    page: Hatchery.Candling.Page22,
    type: 'hatchery',
    cate: 'candling',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/23',
    page: Hatchery.Candling.Page23,
    type: 'hatchery',
    cate: 'candling',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/24',
    page: Hatchery.Candling.Page24,
    type: 'hatchery',
    cate: 'candling',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/25',
    page: Hatchery.Candling.Page25,
    type: 'hatchery',
    cate: 'candling',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/26',
    page: Hatchery.Candling.Page26,
    type: 'hatchery',
    cate: 'candling',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/27',
    page: Hatchery.Candling.Page27,
    type: 'hatchery',
    cate: 'candling',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/28',
    page: Hatchery.Candling.Page28,
    type: 'hatchery',
    cate: 'candling',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/29',
    page: Hatchery.Candling.Page29,
    type: 'hatchery',
    cate: 'candling',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/candling/30',
    page: Hatchery.Candling.Page30,
    type: 'hatchery',
    cate: 'candling',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('캔들링'),
    cate_desc: i18n.t('입란한 계란을 검란해 해처리에 넣습니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/01',
    page: Hatchery.Hatcher.Page01,
    type: 'hatchery',
    cate: 'hatcher',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/02',
    page: Hatchery.Hatcher.Page02,
    type: 'hatchery',
    cate: 'hatcher',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/03',
    page: Hatchery.Hatcher.Page03,
    type: 'hatchery',
    cate: 'hatcher',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/04',
    page: Hatchery.Hatcher.Page04,
    type: 'hatchery',
    cate: 'hatcher',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/05',
    page: Hatchery.Hatcher.Page05,
    type: 'hatchery',
    cate: 'hatcher',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/06',
    page: Hatchery.Hatcher.Page06,
    type: 'hatchery',
    cate: 'hatcher',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/07',
    page: Hatchery.Hatcher.Page07,
    type: 'hatchery',
    cate: 'hatcher',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/08',
    page: Hatchery.Hatcher.Page08,
    type: 'hatchery',
    cate: 'hatcher',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/09',
    page: Hatchery.Hatcher.Page09,
    type: 'hatchery',
    cate: 'hatcher',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/10',
    page: Hatchery.Hatcher.Page10,
    type: 'hatchery',
    cate: 'hatcher',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/11',
    page: Hatchery.Hatcher.Page11,
    type: 'hatchery',
    cate: 'hatcher',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/12',
    page: Hatchery.Hatcher.Page12,
    type: 'hatchery',
    cate: 'hatcher',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/13',
    page: Hatchery.Hatcher.Page13,
    type: 'hatchery',
    cate: 'hatcher',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/14',
    page: Hatchery.Hatcher.Page14,
    type: 'hatchery',
    cate: 'hatcher',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/15',
    page: Hatchery.Hatcher.Page15,
    type: 'hatchery',
    cate: 'hatcher',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/16',
    page: Hatchery.Hatcher.Page16,
    type: 'hatchery',
    cate: 'hatcher',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/17',
    page: Hatchery.Hatcher.Page17,
    type: 'hatchery',
    cate: 'hatcher',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/18',
    page: Hatchery.Hatcher.Page18,
    type: 'hatchery',
    cate: 'hatcher',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/19',
    page: Hatchery.Hatcher.Page19,
    type: 'hatchery',
    cate: 'hatcher',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/20',
    page: Hatchery.Hatcher.Page20,
    type: 'hatchery',
    cate: 'hatcher',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/21',
    page: Hatchery.Hatcher.Page21,
    type: 'hatchery',
    cate: 'hatcher',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/22',
    page: Hatchery.Hatcher.Page22,
    type: 'hatchery',
    cate: 'hatcher',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/23',
    page: Hatchery.Hatcher.Page23,
    type: 'hatchery',
    cate: 'hatcher',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/24',
    page: Hatchery.Hatcher.Page24,
    type: 'hatchery',
    cate: 'hatcher',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/25',
    page: Hatchery.Hatcher.Page25,
    type: 'hatchery',
    cate: 'hatcher',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/26',
    page: Hatchery.Hatcher.Page26,
    type: 'hatchery',
    cate: 'hatcher',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/27',
    page: Hatchery.Hatcher.Page27,
    type: 'hatchery',
    cate: 'hatcher',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/28',
    page: Hatchery.Hatcher.Page28,
    type: 'hatchery',
    cate: 'hatcher',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/29',
    page: Hatchery.Hatcher.Page29,
    type: 'hatchery',
    cate: 'hatcher',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/hatcher/30',
    page: Hatchery.Hatcher.Page30,
    type: 'hatchery',
    cate: 'hatcher',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화기'),
    cate_desc: i18n.t('해처리에서 태어난 병아리의 등급을 입력합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/transegg/00',
    page: Hatchery.Transegg.Page00,
    type: 'hatchery',
    cate: 'transegg',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('출고/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/01',
    page: Hatchery.Transegg.Page01,
    type: 'hatchery',
    cate: 'transegg',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/02',
    page: Hatchery.Transegg.Page02,
    type: 'hatchery',
    cate: 'transegg',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/03',
    page: Hatchery.Transegg.Page03,
    type: 'hatchery',
    cate: 'transegg',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/04',
    page: Hatchery.Transegg.Page04,
    type: 'hatchery',
    cate: 'transegg',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/05',
    page: Hatchery.Transegg.Page05,
    type: 'hatchery',
    cate: 'transegg',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/06',
    page: Hatchery.Transegg.Page06,
    type: 'hatchery',
    cate: 'transegg',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/07',
    page: Hatchery.Transegg.Page07,
    type: 'hatchery',
    cate: 'transegg',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/08',
    page: Hatchery.Transegg.Page08,
    type: 'hatchery',
    cate: 'transegg',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/09',
    page: Hatchery.Transegg.Page09,
    type: 'hatchery',
    cate: 'transegg',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/10',
    page: Hatchery.Transegg.Page10,
    type: 'hatchery',
    cate: 'transegg',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/11',
    page: Hatchery.Transegg.Page11,
    type: 'hatchery',
    cate: 'transegg',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/12',
    page: Hatchery.Transegg.Page12,
    type: 'hatchery',
    cate: 'transegg',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/13',
    page: Hatchery.Transegg.Page13,
    type: 'hatchery',
    cate: 'transegg',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/14',
    page: Hatchery.Transegg.Page14,
    type: 'hatchery',
    cate: 'transegg',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/15',
    page: Hatchery.Transegg.Page15,
    type: 'hatchery',
    cate: 'transegg',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/16',
    page: Hatchery.Transegg.Page16,
    type: 'hatchery',
    cate: 'transegg',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/17',
    page: Hatchery.Transegg.Page17,
    type: 'hatchery',
    cate: 'transegg',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/18',
    page: Hatchery.Transegg.Page18,
    type: 'hatchery',
    cate: 'transegg',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/19',
    page: Hatchery.Transegg.Page19,
    type: 'hatchery',
    cate: 'transegg',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/20',
    page: Hatchery.Transegg.Page20,
    type: 'hatchery',
    cate: 'transegg',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/21',
    page: Hatchery.Transegg.Page21,
    type: 'hatchery',
    cate: 'transegg',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/22',
    page: Hatchery.Transegg.Page22,
    type: 'hatchery',
    cate: 'transegg',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/23',
    page: Hatchery.Transegg.Page23,
    type: 'hatchery',
    cate: 'transegg',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/24',
    page: Hatchery.Transegg.Page24,
    type: 'hatchery',
    cate: 'transegg',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/25',
    page: Hatchery.Transegg.Page25,
    type: 'hatchery',
    cate: 'transegg',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/26',
    page: Hatchery.Transegg.Page26,
    type: 'hatchery',
    cate: 'transegg',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/27',
    page: Hatchery.Transegg.Page27,
    type: 'hatchery',
    cate: 'transegg',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/28',
    page: Hatchery.Transegg.Page28,
    type: 'hatchery',
    cate: 'transegg',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/29',
    page: Hatchery.Transegg.Page29,
    type: 'hatchery',
    cate: 'transegg',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/transegg/30',
    page: Hatchery.Transegg.Page30,
    type: 'hatchery',
    cate: 'transegg',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('달걀을 출고 합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/transchick/00',
    page: Hatchery.Transchick.Page00,
    type: 'hatchery',
    cate: 'transchick',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('출고/병아리'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/01',
    page: Hatchery.Transchick.Page01,
    type: 'hatchery',
    cate: 'transchick',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/02',
    page: Hatchery.Transchick.Page02,
    type: 'hatchery',
    cate: 'transchick',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/03',
    page: Hatchery.Transchick.Page03,
    type: 'hatchery',
    cate: 'transchick',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/04',
    page: Hatchery.Transchick.Page04,
    type: 'hatchery',
    cate: 'transchick',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/05',
    page: Hatchery.Transchick.Page05,
    type: 'hatchery',
    cate: 'transchick',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/06',
    page: Hatchery.Transchick.Page06,
    type: 'hatchery',
    cate: 'transchick',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/07',
    page: Hatchery.Transchick.Page07,
    type: 'hatchery',
    cate: 'transchick',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/08',
    page: Hatchery.Transchick.Page08,
    type: 'hatchery',
    cate: 'transchick',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/09',
    page: Hatchery.Transchick.Page09,
    type: 'hatchery',
    cate: 'transchick',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/10',
    page: Hatchery.Transchick.Page10,
    type: 'hatchery',
    cate: 'transchick',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/11',
    page: Hatchery.Transchick.Page11,
    type: 'hatchery',
    cate: 'transchick',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/12',
    page: Hatchery.Transchick.Page12,
    type: 'hatchery',
    cate: 'transchick',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/13',
    page: Hatchery.Transchick.Page13,
    type: 'hatchery',
    cate: 'transchick',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/14',
    page: Hatchery.Transchick.Page14,
    type: 'hatchery',
    cate: 'transchick',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/15',
    page: Hatchery.Transchick.Page15,
    type: 'hatchery',
    cate: 'transchick',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/16',
    page: Hatchery.Transchick.Page16,
    type: 'hatchery',
    cate: 'transchick',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/17',
    page: Hatchery.Transchick.Page17,
    type: 'hatchery',
    cate: 'transchick',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/18',
    page: Hatchery.Transchick.Page18,
    type: 'hatchery',
    cate: 'transchick',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/19',
    page: Hatchery.Transchick.Page19,
    type: 'hatchery',
    cate: 'transchick',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/20',
    page: Hatchery.Transchick.Page20,
    type: 'hatchery',
    cate: 'transchick',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/21',
    page: Hatchery.Transchick.Page21,
    type: 'hatchery',
    cate: 'transchick',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/22',
    page: Hatchery.Transchick.Page22,
    type: 'hatchery',
    cate: 'transchick',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/23',
    page: Hatchery.Transchick.Page23,
    type: 'hatchery',
    cate: 'transchick',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/24',
    page: Hatchery.Transchick.Page24,
    type: 'hatchery',
    cate: 'transchick',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/25',
    page: Hatchery.Transchick.Page25,
    type: 'hatchery',
    cate: 'transchick',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/26',
    page: Hatchery.Transchick.Page26,
    type: 'hatchery',
    cate: 'transchick',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/27',
    page: Hatchery.Transchick.Page27,
    type: 'hatchery',
    cate: 'transchick',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/28',
    page: Hatchery.Transchick.Page28,
    type: 'hatchery',
    cate: 'transchick',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/29',
    page: Hatchery.Transchick.Page29,
    type: 'hatchery',
    cate: 'transchick',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/transchick/30',
    page: Hatchery.Transchick.Page30,
    type: 'hatchery',
    cate: 'transchick',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('부화장/달걀'),
    cate_desc: i18n.t('병아리를 출고 합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  },

  {
    uri: '/hatchery/cutting/00',
    page: Hatchery.Cutting.Page00,
    type: 'hatchery',
    cate: 'cutting',
    id: '00',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('Discard와는 또다른 폐기처리 입니다'),
    page_nm: i18n.t('페이지#00'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/01',
    page: Hatchery.Cutting.Page01,
    type: 'hatchery',
    cate: 'cutting',
    id: '01',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#01'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/02',
    page: Hatchery.Cutting.Page02,
    type: 'hatchery',
    cate: 'cutting',
    id: '02',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#02'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/03',
    page: Hatchery.Cutting.Page03,
    type: 'hatchery',
    cate: 'cutting',
    id: '03',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#03'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/04',
    page: Hatchery.Cutting.Page04,
    type: 'hatchery',
    cate: 'cutting',
    id: '04',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#04'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/05',
    page: Hatchery.Cutting.Page05,
    type: 'hatchery',
    cate: 'cutting',
    id: '05',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#05'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/06',
    page: Hatchery.Cutting.Page06,
    type: 'hatchery',
    cate: 'cutting',
    id: '06',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#06'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/07',
    page: Hatchery.Cutting.Page07,
    type: 'hatchery',
    cate: 'cutting',
    id: '07',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#07'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/08',
    page: Hatchery.Cutting.Page08,
    type: 'hatchery',
    cate: 'cutting',
    id: '08',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#08'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/09',
    page: Hatchery.Cutting.Page09,
    type: 'hatchery',
    cate: 'cutting',
    id: '09',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#09'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/10',
    page: Hatchery.Cutting.Page10,
    type: 'hatchery',
    cate: 'cutting',
    id: '10',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#10'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/11',
    page: Hatchery.Cutting.Page11,
    type: 'hatchery',
    cate: 'cutting',
    id: '11',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#11'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/12',
    page: Hatchery.Cutting.Page12,
    type: 'hatchery',
    cate: 'cutting',
    id: '12',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#12'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/13',
    page: Hatchery.Cutting.Page13,
    type: 'hatchery',
    cate: 'cutting',
    id: '13',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#13'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/14',
    page: Hatchery.Cutting.Page14,
    type: 'hatchery',
    cate: 'cutting',
    id: '14',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#14'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/15',
    page: Hatchery.Cutting.Page15,
    type: 'hatchery',
    cate: 'cutting',
    id: '15',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#15'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/16',
    page: Hatchery.Cutting.Page16,
    type: 'hatchery',
    cate: 'cutting',
    id: '16',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#16'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/17',
    page: Hatchery.Cutting.Page17,
    type: 'hatchery',
    cate: 'cutting',
    id: '17',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#17'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/18',
    page: Hatchery.Cutting.Page18,
    type: 'hatchery',
    cate: 'cutting',
    id: '18',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#18'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/19',
    page: Hatchery.Cutting.Page19,
    type: 'hatchery',
    cate: 'cutting',
    id: '19',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#19'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/20',
    page: Hatchery.Cutting.Page20,
    type: 'hatchery',
    cate: 'cutting',
    id: '20',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#20'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/21',
    page: Hatchery.Cutting.Page21,
    type: 'hatchery',
    cate: 'cutting',
    id: '21',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#21'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/22',
    page: Hatchery.Cutting.Page22,
    type: 'hatchery',
    cate: 'cutting',
    id: '22',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#22'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/23',
    page: Hatchery.Cutting.Page23,
    type: 'hatchery',
    cate: 'cutting',
    id: '23',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#23'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/24',
    page: Hatchery.Cutting.Page24,
    type: 'hatchery',
    cate: 'cutting',
    id: '24',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#24'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/25',
    page: Hatchery.Cutting.Page25,
    type: 'hatchery',
    cate: 'cutting',
    id: '25',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#25'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/26',
    page: Hatchery.Cutting.Page26,
    type: 'hatchery',
    cate: 'cutting',
    id: '26',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#26'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/27',
    page: Hatchery.Cutting.Page27,
    type: 'hatchery',
    cate: 'cutting',
    id: '27',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#27'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/28',
    page: Hatchery.Cutting.Page28,
    type: 'hatchery',
    cate: 'cutting',
    id: '28',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#28'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/29',
    page: Hatchery.Cutting.Page29,
    type: 'hatchery',
    cate: 'cutting',
    id: '29',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#29'),
    is_full: false
  },
  {
    uri: '/hatchery/cutting/30',
    page: Hatchery.Cutting.Page30,
    type: 'hatchery',
    cate: 'cutting',
    id: '30',
    type_nm: i18n.t('부화장'),
    cate_nm: i18n.t('커팅'),
    cate_desc: i18n.t('폐기합니다'),
    page_nm: i18n.t('페이지#30'),
    is_full: false
  }
];

export default HatcheryRouteList;
